### ISSUE TITLE
[BUG] DataFrame.read_csv doesn't work with cluster session.

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#1059]
**Describe the bug**

`DataFrame.read_csv` doesn't work with other ops under cluster session.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.
5. Minimized code to reproduce the error.

```python
def h():
    cp = md.read_csv("test.csv", sep="\t")
    # cp = md.DataFrame(pd.read_csv('test.csv', sep="\t"))
    print(cp.head().execute())
    print(cp.merge(cp[['FromNodeId']].set_index('FromNodeId'),
                   how='right', left_on='FromNodeId', right_index=True).execute())

with new_cluster(scheduler_n_process=1, worker_n_process=2,
                shared_memory='20M', web=False) as cluster:
    with new_session(cluster.endpoint).as_default() as sess:
        h()
```

+ `md.read_csv` + no `.head().execute()` works
+ `md.read_csv` + `.head().execute()` doesn't work, note that after `.head().execute()`, the `cp` IS NOT a `DataFrameFetch` value
+ `pd.read_csv` works, with or without `.head().execute()`

The error stack trace:

```python
ERROR:mars.utils:Unexpected exception occurred in GraphActor.set_operand_worker. op_key='94d928c744df90b0b6dc58870efa3e21'
Traceback (most recent call last):
  File "/Users/linzhu.ht/mars-dev/mars/utils.py", line 334, in _wrapped
    return func(*args, **kwargs)
  File "/Users/linzhu.ht/mars-dev/mars/scheduler/graph.py", line 1060, in set_operand_worker
    self._graph_meta_ref.update_op_worker(op_key, op_info['op_name'], worker,
KeyError: 'op_name'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 86, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    cpdef object fire_run(self):
  File "mars/actors/pool/gevent_pool.pyx", line 89, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    with self.lock:
  File "mars/actors/pool/gevent_pool.pyx", line 100, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    raise
  File "mars/actors/pool/gevent_pool.pyx", line 94, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    res = actor.on_receive(message_ctx.message)
  File "mars/actors/core.pyx", line 112, in mars.actors.core._FunctionActor.on_receive
    cpdef on_receive(self, message):
  File "mars/actors/core.pyx", line 114, in mars.actors.core._FunctionActor.on_receive
    return getattr(self, method)(*args, **kwargs)
  File "/Users/linzhu.ht/mars-dev/mars/utils.py", line 334, in _wrapped
    return func(*args, **kwargs)
  File "/Users/linzhu.ht/mars-dev/mars/scheduler/graph.py", line 1060, in set_operand_worker
    self._graph_meta_ref.update_op_worker(op_key, op_info['op_name'], worker,
KeyError: 'op_name'

Traceback (most recent call last):
  File "/Users/linzhu.ht/mars-dev/mars/scheduler/assigner.py", line 310, in allocate_top_resources
    reject_workers=reject_workers)
  File "/Users/linzhu.ht/mars-dev/mars/utils.py", line 334, in _wrapped
    return func(*args, **kwargs)
  File "/Users/linzhu.ht/mars-dev/mars/scheduler/assigner.py", line 358, in _allocate_resource
    raise DependencyMissing('Dependency missing for operand %s' % op_key)
mars.errors.DependencyMissing: 'Dependency missing for operand 4c509bedc251f395144060fc54010fa8'
```

The content of `test.csv` is:

```
FromNodeId	ToNodeId
0	1
0	2
0	3
0	4
0	5
1	0
1	2
1	4
1	5
```

**Expected behavior**

`DataFrame.read_csv` should work as expected.

**Additional context**

This might be related to #1055, but it shows a completely different error stacktrace.

**Comment by sighingnow** [comment]
Another case that #1062 doesn't fix:

```python
def r():
    cp = md.read_csv(os.path.abspath("test.csv"), sep="\t")
    cp.head().execute()
    mm = md.read_csv(os.path.abspath("test.csv"), sep="\t")
    mm.head().execute()
    cp_video = cp[cp.FromNodeId > mm.ToNodeId]
    cp_video.head().execute()
    print(cp_video[['FromNodeId', 'ToNodeId']].execute())
```
