### ISSUE TITLE
[BUG] got an IndexError when setitem with mt.ones

### ISSUE THREAD

**Issue by NJUPole** [mars-project/mars#115]
**Describe the bug**
When submit setitem expressions to cluster, `GraphActor.prepare_graph` raised `IndexError`.

**To Reproduce**
```
In [4]: a = mt.random.rand(10, 10)

In [5]: a[:5, :5] = mt.ones((5, 5))

In [6]: a[5:10, 5:10] = mt.ones((5, 5)) * 2

In [7]: cluster.session.run(a)
Failed to start graph execution.
Traceback (most recent call last):
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 239, in execute_graph
    self.prepare_graph()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 416, in prepare_graph
    for n in tensor_to_tiled[tk][-1].chunks:
IndexError: list index out of range
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 88, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 91, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 102, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 96, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/core.pyx", line 108, in mars.actors.core.FunctionActor.on_receive
  File "mars/actors/core.pyx", line 110, in mars.actors.core.FunctionActor.on_receive
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 239, in execute_graph
    self.prepare_graph()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 416, in prepare_graph
    for n in tensor_to_tiled[tk][-1].chunks:
IndexError: list index out of range
2019-01-08T06:55:42Z <Greenlet "Greenlet-0" at 0x320317c48: <built-in method fire_run of mars.actors.pool.gevent_pool.ActorExecutionContext object at 0x32047c458>> failed with IndexError

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-7-06ec9ebba039> in <module>()
----> 1 cluster.session.run(a)

~/Documents/mars_dev/mars/mars/session.py in run(self, *tensors, **kw)
    110         # execute the non-executed tensors
    111         if idx_to_run_tensors:
--> 112             execute_result = self._sess.run(*idx_to_run_tensors.values(), **kw)
    113             if execute_result:
    114                 # fetch is True

~/Documents/mars_dev/mars/mars/deploy/local/session.py in run(self, *tensors, **kw)
     71             if graph_state == GraphState.FAILED:
     72                 # TODO(qin): add traceback
---> 73                 raise SystemError('Graph execution failed with unknown reason')
     74 
     75         if 0 < timeout < time.time() - exec_start_time:

SystemError: Graph execution failed with unknown reason
```
however it works when value is `mt.ones((5, 5))` without multiply by 2.
```
In [4]: a = mt.random.rand(10, 10)

In [5]: a[:5, :5] = mt.ones((5, 5))

In [6]: a[5:10, 5:10] = mt.ones((5, 5))

In [7]: cluster.session.run(a)
Out[7]: 
array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        0.71645692, 0.73310965, 0.27332111, 0.53404958, 0.43818169],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.7654411 , 0.06258097, 0.32313892, 0.67699528, 0.83672464],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.38562723, 0.51791558, 0.92523203, 0.88885575, 0.88152387],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.85278501, 0.15031892, 0.36973803, 0.79156834, 0.25785725],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.01598595, 0.35417422, 0.51862623, 0.44287278, 0.79882332],
       [0.98480177, 0.88607345, 0.78764026, 0.48536084, 0.59666905,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.63707366, 0.88748085, 0.85763743, 0.64301722, 0.58708402,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.91564735, 0.57704163, 0.41733464, 0.17699732, 0.17902524,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.6412424 , 0.56966859, 0.98603185, 0.29877888, 0.64962717,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.22425854, 0.04535534, 0.4892396 , 0.78086597, 0.35686183,
        1.        , 1.        , 1.        , 1.        , 1.        ]])
```
**Expected behavior**
It should behave like run with local session.
```
In [1]: import mars.tensor as mt

In [2]: a = mt.random.rand(10, 10)

In [3]: a[:5, :5] = mt.ones((5, 5))

In [4]: a[5:10, 5:10] = mt.ones((5, 5)) * 2

In [5]: a.execute()
Out[5]: 
array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        0.32666468, 0.17133841, 0.78110928, 0.3470744 , 0.75992179],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.80793372, 0.28223076, 0.48451418, 0.20444977, 0.01312504],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.3446098 , 0.15119387, 0.53543721, 0.64302594, 0.24665612],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.36354404, 0.64536075, 0.70544883, 0.35930292, 0.18954646],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        0.27617278, 0.70748526, 0.5806906 , 0.23309319, 0.2004623 ],
       [0.52383834, 0.33428529, 0.72989358, 0.88056503, 0.9267791 ,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [0.43696731, 0.04261789, 0.7842462 , 0.79119168, 0.67635289,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [0.5069902 , 0.02869844, 0.96092322, 0.56741621, 0.00999291,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [0.47154552, 0.17418114, 0.94618458, 0.64845816, 0.37390886,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [0.91325706, 0.28710271, 0.46964672, 0.92901795, 0.82593861,
        2.        , 2.        , 2.        , 2.        , 2.        ]])
```

**Comment by NJUPole** [comment]
Actually, the issue was resolved by #103 .
