### ISSUE TITLE
[BUG] Bool indexing can't work on cluster mode

### ISSUE THREAD

**Issue by NJUPole** [mars-project/mars#117]
**Describe the bug**
When submitted a graph contains bool indexing like `b = a[a < 0.5]`, scheduler raised an error in `create_operand_actors`, also another error occurred in `stop_graph` and not be caught.

**To Reproduce**
```
In [4]: a = mt.random.rand(10, 10)

In [5]: b = a[a < 0.5]

In [6]: cluster.session.run(b)
Failed to start graph execution.
Traceback (most recent call last):
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 248, in execute_graph
    self.create_operand_actors()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 646, in create_operand_actors
    op_info['output_size'] = int(output_size)
ValueError: cannot convert float NaN to integer
Traceback (most recent call last):
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 248, in execute_graph
    self.create_operand_actors()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 646, in create_operand_actors
    op_info['output_size'] = int(output_size)
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 88, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 91, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 102, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 96, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/core.pyx", line 108, in mars.actors.core.FunctionActor.on_receive
  File "mars/actors/core.pyx", line 110, in mars.actors.core.FunctionActor.on_receive
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 254, in execute_graph
    self.stop_graph()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/graph.py", line 276, in stop_graph
    if self._operand_infos[chunk.op.key]['state'] in \
KeyError: 'state'
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 88, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 91, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 102, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 96, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/core.pyx", line 108, in mars.actors.core.FunctionActor.on_receive
  File "mars/actors/core.pyx", line 110, in mars.actors.core.FunctionActor.on_receive
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/operand.py", line 262, in stop_operand
    self.state = OperandState.CANCELLING
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/scheduler/operand.py", line 218, in state
    self._graph_ref.set_operand_state(self._op_key, value.value, _tell=True, _wait=False),
AttributeError: 'NoneType' object has no attribute 'set_operand_state'
2019-01-10T07:35:29Z <Greenlet "Greenlet-0" at 0x119fd6e48: <built-in method fire_run of mars.actors.pool.gevent_pool.ActorExecutionContext object at 0x31a40fd68>> failed with AttributeError
2019-01-10T07:35:29Z <Greenlet "Greenlet-0" at 0x119fd6d48: <built-in method fire_run of mars.actors.pool.gevent_pool.ActorExecutionContext object at 0x31a3f28b8>> failed with KeyError
```

**Expected behavior**
Expected as run on thread mode:
```
In [1]: import mars.tensor as mt

In [2]: a = mt.random.rand(10, 10)

In [3]: b = a[a < 0.5]

In [4]: b.execute()
Out[4]: 
array([0.1005618 , 0.25126272, 0.25210696, 0.21150309, 0.07146362,
       0.39054374, 0.02661607, 0.16613239, 0.0907595 , 0.14755511,
       0.49057574, 0.02507875, 0.26802079, 0.05933454, 0.37048073,
       0.45108296, 0.28699272, 0.12298096, 0.46602457, 0.10055897,
       0.3471593 , 0.23631087, 0.02345734, 0.10802468, 0.39142212,
       0.40125109, 0.45736915, 0.37541724, 0.02056482, 0.4713944 ,
       0.38820422, 0.01525971, 0.4863198 , 0.08759706, 0.3516776 ,
       0.00339117, 0.47651939, 0.33947519, 0.14709538, 0.16620697,
       0.09169262, 0.3327405 , 0.36628693, 0.10238781, 0.38438336,
       0.09946711, 0.31808827, 0.25405009, 0.19771359, 0.00521404,
       0.26727615])
```

**Additional context**
The shape of the bool indexing tensor is undetermined before execution, so `nbytes` is not available when calculate the tensor's `output_size`, `Chunk` may provide estimated size for operator similar to bool indexing.

**Comment by NJUPole** [comment]
Should we add something like `_estimated_size` in `ChunkData`'s slots ?

**Comment by chineking** [comment]
> Should we add something like `_estimated_size` in `ChunkData`'s slots ?

I suggest add `_rough_size` property.
