### ISSUE TITLE
[BUG] Serialize failed if FetchDataFrame's output_type is type of list

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#1385]
**Describe the bug**
Serialize failed when serialize fetch DataFrame.

**To Reproduce**
``` Python
raw = pd.DataFrame(np.random.rand(100, 3), columns=list('abc'))
df = md.DataFrame(raw)
bins = [0.006 * i for i in range(0, 101)]
cut = md.cut(df['a'], bins)
cut.execute()
# test fetch replacement
r = cut.iloc[:3].execute()
expected = pd.cut(raw['a'], bins).iloc[:3]
pd.testing.assert_series_equal(r.fetch(), expected)
```
run the above code in cluster mode will raise error:
```
Error
Traceback (most recent call last):
  File "mars/serialize/jsonserializer.pyx", line 588, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
  File "mars/serialize/jsonserializer.pyx", line 522, in mars.serialize.jsonserializer.JsonSerializeProvider._on_serial
AttributeError: 'list' object has no attribute 'value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1191, in patched
    return func(*args, **keywargs)
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/deploy/local/tests/test_cluster.py", line 553, in testFetchDataFrame
    r = cut.iloc[:3].execute()
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/core.py", line 561, in execute
    self._data.execute(session, **kw)
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/core.py", line 370, in execute
    session.run(self, **kw)
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/session.py", line 428, in run
    result = self._sess.run(*tileables, **kw)
  File "/Users/hekaisheng/Documents/mars_dev/mars/mars/session.py", line 287, in run
    self._api.submit_graph(self._session_id, json.dumps(graph.to_json(), separators=(',', ':')),
  File "mars/graph.pyx", line 452, in mars.graph.DirectedGraph.to_json
  File "mars/serialize/core.pyx", line 689, in mars.serialize.core.Serializable.to_json
  File "mars/serialize/core.pyx", line 660, in mars.serialize.core.Serializable.serialize
  File "mars/serialize/core.pyx", line 786, in mars.serialize.core.Provider.serialize_model
  File "mars/serialize/core.pyx", line 153, in mars.serialize.core.Field.serialize
  File "mars/serialize/core.pyx", line 154, in mars.serialize.core.Field.serialize
  File "mars/serialize/jsonserializer.pyx", line 584, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
  File "mars/serialize/jsonserializer.pyx", line 529, in mars.serialize.jsonserializer.JsonSerializeProvider._serialize_reference
  File "mars/serialize/core.pyx", line 724, in mars.serialize.core.AttributeAsDict.serialize
  File "mars/serialize/core.pyx", line 791, in mars.serialize.core.Provider.serialize_attribute_as_dict
  File "mars/serialize/core.pyx", line 786, in mars.serialize.core.Provider.serialize_model
  File "mars/serialize/core.pyx", line 153, in mars.serialize.core.Field.serialize
  File "mars/serialize/core.pyx", line 154, in mars.serialize.core.Field.serialize
  File "mars/serialize/jsonserializer.pyx", line 591, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
  File "mars/serialize/jsonserializer.pyx", line 588, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
  File "mars/serialize/jsonserializer.pyx", line 522, in mars.serialize.jsonserializer.JsonSerializeProvider._on_serial
AttributeError: Fail to serialize field `object_type` for DataFrameFetch <key=2670416e321242115cba4010ed862ce9>, reason: 'list' object has no attribute 'value'

```

**Expected behavior**

**Additional context**

**Comment by hekaisheng** [comment]
Closed by #1286 .
