### ISSUE TITLE
No gpu found error

### ISSUE THREAD

**Issue by tqslj2** [mars-project/mars#1461]
(rapids) root@ctpai-node1:~# python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mars
>>> import mars.tensor as mt
>>> a=mt.random.rand(10,10,gpu=True)
>>> a.sum().execute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/mars/core.py", line 580, in execute
    self._data.execute(session, **kw)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/mars/core.py", line 370, in execute
    session.run(self, **kw)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/mars/session.py", line 461, in run
    result = self._sess.run(*tileables, **kw)
  File "/opt/conda/envs/rapids/lib/python3.6/site-packages/mars/session.py", line 99, in run
    raise RuntimeError('No GPU found for execution')
RuntimeError: No GPU found for execution

i can see there is a same issue before but i didn't understand how to resolve it, anyone have a more specific solution? thanks a loooot !!!

**Comment by qinxuye** [comment]
Check #1370 if it's duplicated issue.

For LInux, you can set `LD_LIBRARY_PATH` manually to see if you can resolve the issue.

**Comment by qinxuye** [comment]
This issue must have been resolved in v0.4.6 as well as v0.5.0rc1.

`pip install pymars>=0.4.6` to verify.
