### ISSUE TITLE
[BUG]TypeError: Unsupported type <class 'numpy.ndarray'>

### ISSUE THREAD

**Issue by YoshieraHuang** [mars-project/mars#1517]
## Describe the bug
I am using mars for scientific calculations. I meet this errors when i execute an intermediate expression.
```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p2d.calc_peaks()
  File "/home/jasper/PDAC/pdac/simu2d.py", line 172, in calc_peaks
    print(hkls.execute())
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/core.py", line 582, in execute
    self._data.execute(session, **kw)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/core.py", line 370, in execute
    session.run(self, **kw)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/session.py", line 462, in run
    result = self._sess.run(*tileables, **kw)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/session.py", line 107, in run
    res = self._executor.execute_tileables(tileables, **kw)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/utils.py", line 408, in _wrapped
    return func(*args, **kwargs)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/utils.py", line 502, in inner
    return func(*args, **kwargs)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/executor.py", line 880, in execute_tileables
    chunk_result=chunk_result)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/executor.py", line 690, in execute_graph
    res = graph_execution.execute(retval)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/executor.py", line 571, in execute
    future.result()
  File "/home/jasper/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/jasper/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jasper/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/executor.py", line 443, in _execute_operand
    Executor.handle(first_op, results, self._mock)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/executor.py", line 641, in handle
    return runner(results, op)
  File "/home/jasper/anaconda3/lib/python3.7/site-packages/mars/tensor/fuse/cp.py", line 42, in execute
    ctx[chunk.key] = func(*[ctx[i.key] for i in op.inputs])
  File "cupy/core/_kernel.pyx", line 605, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 90, in cupy.core._kernel._preprocess_args
TypeError: Unsupported type <class 'numpy.ndarray'>
```
The input arguments are tensor. If I execute the arguments first, the error is not raised. Could you give me a hint that why this error is raised.

**Comment by qinxuye** [comment]
Looks like you are trying to mix tensors from both CPU and GPU. You can call `to_gpu` or `to_cpu` to move data. You can check if there is any code that may cause the error.

**Comment by YoshieraHuang** [comment]
> Looks like you are trying to mix tensors from both CPU and GPU. You can call `to_gpu` or `to_cpu` to move data. You can check if there is any code that may cause the error.

I changed the calculation process and the error is not raised. Thanks a lot for your reply.
