### ISSUE TITLE
[BUG] Run the example code hangs in distributed mode

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#1698]
**Describe the bug**
Create a Mars cluster and run the code in readme:
``` Python
import mars.tensor as mt
N = 200_000_000
a = mt.random.uniform(-1, 1, size=(N, 2))
print(((mt.linalg.norm(a, axis=1) < 1)
        .sum() * 4 / N).execute())
```

it hangs and error be found in server client:
```
2020-11-09 21:30:22,053 mars.scheduler.operands.common 97 ERROR    Attempt 1: Unexpected error KeyError occurred in executing operand 230bef1901408a5f9134f34444918898 in 11.238.146.2:35131
Traceback (most recent call last):
  File "/home/admin/work/public-mars-0.5.4.zip/mars/promise.py", line 378, in _wrapped
    return func(*args, **kwargs)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/utils.py", line 365, in _wrapped
    return func(*args, **kwargs)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/worker/execution.py", line 564, in execute_graph
    quota_request = self._prepare_quota_request(session_id, graph_key)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/worker/execution.py", line 249, in _prepare_quota_request
    memory_estimations = self._estimate_calc_memory(session_id, graph_key)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/worker/execution.py", line 213, in _estimate_calc_memory
    res = executor.execute_graph(graph_record.graph, graph_record.chunk_targets, mock=True)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 690, in execute_graph
    res = graph_execution.execute(retval)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 571, in execute
    future.result()
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 186, in result
    raise self._exc_info[1] from None
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 198, in submit
    return self._MockResult(fn(*args, **kwargs))
  File "/home/admin/work/public-mars-0.5.4.zip/mars/utils.py", line 439, in _inner
    return func(*args, **kwargs)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 443, in _execute_operand
    Executor.handle(first_op, results, self._mock)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 641, in handle
    return runner(results, op)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/tensor/fuse/ne.py", line 75, in estimate_size
    estimate_fuse_size(ctx, op)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/tensor/fuse/core.py", line 49, in estimate_fuse_size
    results = executor.execute_graph(dag, output_keys, mock=True, no_intermediate=True)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 690, in execute_graph
    res = graph_execution.execute(retval)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 571, in execute
    future.result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/utils.py", line 439, in _inner
    return func(*args, **kwargs)
  File "/home/admin/work/public-mars-0.5.4.zip/mars/executor.py", line 486, in _execute_operand
    del results[dep_key]
KeyError: '94e11781368129674925eb2d4ae093bf'
```

**Comment by hekaisheng** [comment]
The bug has been fixed in master(https://github.com/mars-project/mars/pull/1541/commits/66be75170184919935ca06ceed2c526d30553bda), I will submit a PR to fix it in branch v0.5.
