### ISSUE TITLE
[BUG][DISTRIBUTED] client will hang if submit the same graph again

### ISSUE THREAD

**Issue by NJUPole** [mars-project/mars#17]
**Describe the bug**
if we resubmit the same tensor by session, the client will hang, at the same time, i found scheduler raise an  error `ActorAlreadyExist`, which i think can be solved by prune existed operand.

**To Reproduce**
I creat a distributed environment with 1 worker.

```
In [1]: import mars.tensor as mt

In [2]: from mars.session import new_session

In [3]: session = new_session('http://0.0.0.0:33335')

In [4]: a = mt.ones((10, 10)) + 1

In [5]: session.run(a)
Out[5]: 
array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [6]: session.run(a)

```
the client hang when execute line 6, and scheduler log shows:
```
Creating operand actors for graph 93ba7372-e748-40ab-af14-6c250f845ba4
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 88, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 91, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 102, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/pool/gevent_pool.pyx", line 96, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
  File "mars/actors/core.pyx", line 108, in mars.actors.core.FunctionActor.on_receive
  File "mars/actors/core.pyx", line 110, in mars.actors.core.FunctionActor.on_receive
  File "/Users/hekaisheng/Documents/mars/mars/scheduler/graph.py", line 156, in execute_graph
    self.create_operand_actors()
  File "/Users/hekaisheng/Documents/mars/mars/scheduler/graph.py", line 569, in create_operand_actors
    [future.result() for future in itertools.chain(six.itervalues(op_refs), [write_future])]
  File "/Users/hekaisheng/Documents/mars/mars/scheduler/graph.py", line 569, in <listcomp>
    [future.result() for future in itertools.chain(six.itervalues(op_refs), [write_future])]
  File "src/gevent/event.py", line 457, in gevent._event.AsyncResult.result
  File "src/gevent/event.py", line 381, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 399, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 379, in gevent._event.AsyncResult._raise_exception
  File "/Users/hekaisheng/miniconda3/lib/python3.6/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "mars/actors/pool/gevent_pool.pyx", line 758, in mars.actors.pool.gevent_pool.Communicator._create_local_actor
  File "mars/actors/pool/gevent_pool.pyx", line 237, in mars.actors.pool.gevent_pool.LocalActorPool.create_actor
mars.actors.errors.ActorAlreadyExist: Actor s:operator$2724de06-fc4a-11e8-8d24-47a7eeef77d5$c84e3ef10df7fabaf2dc028149609284 already exist, cannot create

```

**Comment by chineking** [comment]
What's the behavior of **compute on the executed tensor**?

e.g.

```python
a = mt.ones((10, 10)) + 1
session.run(a)

b = a + 1
session.run(b)
```

**Comment by chineking** [comment]
I guess maybe it's the same error as the same graph.

The issue can be considered from two sides.

1. from the client side, we don't need to submit the entire tensor graph, we must have known which part of the tensor graph could have been executed
2. from the server side, we may need to skip the OperandActor which have been created.

**Comment by NJUPole** [comment]
in #80, it resolves the issue by check whether tensor has been executed, when same graph is submitted, session will fetch data from server instead of rerun the graph.
