### ISSUE TITLE
[BUG] XGBoost and LightGBM training failed in distributed mode

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#1740]
**Describe the bug**
It failed if inputs are dataframes when training lightgbm model in distributed mode.

**To Reproduce**
```python
import mars.dataframe as md
import mars.tensor as mt
from mars.learn.contrib.xgboost import XGBClassifier

rs = mt.random.RandomState(0)
X = md.DataFrame(rs.rand(n_rows, n_columns, chunk_size=chunk_size))
y = md.Series(rs.rand(n_rows, chunk_size=chunk_size) * 10).astype(mt.int32))
classifier = XGBClassifier(verbosity=1, n_estimators=2)
classifier.fit(X, y, eval_set=[(X, y)], session=sess, run_kwargs=run_kwargs)
```
```
Error
Traceback (most recent call last):
  File "/Users/wenjun.swj/Code/mars/mars/scheduler/graph.py", line 410, in _execute_graph
    self.prepare_graph(compose=compose)
  File "/Users/wenjun.swj/Code/mars/mars/utils.py", line 377, in _wrapped
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/scheduler/graph.py", line 646, in prepare_graph
    cur_chunk_graph = chunk_graph_builder.build(
  File "/Users/wenjun.swj/Code/mars/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 347, in build
    chunk_graph = super().build(
  File "/Users/wenjun.swj/Code/mars/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 262, in build
    self._on_tile_failure(tileable_data.op, exc_info)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 301, in inner
    raise exc_info[1].with_traceback(exc_info[2]) from None
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 242, in build
    tiled = self._tile(tileable_data, tileable_graph)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 337, in _tile
    return super()._tile(tileable_data, tileable_graph)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 203, in _tile
    tds = on_tile(tileable_data.op.outputs, tds)
  File "/Users/wenjun.swj/Code/mars/mars/scheduler/graph.py", line 630, in on_tile
    return self.context.wraps(handler.dispatch)(first.op)
  File "/Users/wenjun.swj/Code/mars/mars/context.py", line 72, in h
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/tiles.py", line 119, in dispatch
    tiled = op_cls.tile(op)
  File "/Users/wenjun.swj/Code/mars/mars/learn/contrib/xgboost/dmatrix.py", line 257, in tile
    return cls._tile_single_output(op)
  File "/Users/wenjun.swj/Code/mars/mars/learn/contrib/xgboost/dmatrix.py", line 227, in _tile_single_output
    data_chunk = concat_chunks(chunks[0])
  File "/Users/wenjun.swj/Code/mars/mars/learn/utils/core.py", line 33, in concat_chunks
    tileable = chunks[0].op.create_tileable_from_chunks(chunks)
  File "/Users/wenjun.swj/Code/mars/mars/dataframe/operands.py", line 212, in create_tileable_from_chunks
    params = cls._calc_dataframe_params(chunk_index_to_chunk, chunk_shape)
  File "/Users/wenjun.swj/Code/mars/mars/dataframe/operands.py", line 228, in _calc_dataframe_params
    pd_indxes = [chunk_index_to_chunks[i, 0].index_value.to_pandas()
  File "/Users/wenjun.swj/Code/mars/mars/dataframe/operands.py", line 228, in <listcomp>
    pd_indxes = [chunk_index_to_chunks[i, 0].index_value.to_pandas()
KeyError: (2, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wenjun.swj/miniconda3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Users/wenjun.swj/miniconda3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Users/wenjun.swj/miniconda3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/wenjun.swj/Code/mars/mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py", line 71, in testDistributedXGBClassifier
    classifier.fit(X, y, eval_set=[(X, y)], session=sess, run_kwargs=run_kwargs)
  File "/Users/wenjun.swj/Code/mars/mars/learn/contrib/xgboost/classifier.py", line 55, in fit
    result = train(params, dtrain, num_boost_round=self.get_num_boosting_rounds(),
  File "/Users/wenjun.swj/Code/mars/mars/learn/contrib/xgboost/train.py", line 200, in train
    ret = t.execute(session=session, **run_kwargs).fetch(session=session)
  File "/Users/wenjun.swj/Code/mars/mars/core.py", line 379, in execute
    return run()
  File "/Users/wenjun.swj/Code/mars/mars/core.py", line 374, in run
    session.run(self, **kw)
  File "/Users/wenjun.swj/Code/mars/mars/session.py", line 499, in run
    result = self._sess.run(*tileables, **kw)
  File "/Users/wenjun.swj/Code/mars/mars/web/session.py", line 214, in run
    if self._check_response_finished(graph_url, timeout_val):
  File "/Users/wenjun.swj/Code/mars/mars/web/session.py", line 174, in _check_response_finished
    raise ExecutionFailed('Graph execution failed.') from exc
mars.errors.ExecutionFailed: 'Graph execution failed.'
```

```python
import mars.dataframe as md
import mars.tensor as mt
from mars.learn.contrib.lightgbm import LGBMClassifier

x = md.DataFrame(np.random.rand(100, 20), chunk_size=20)
y = md.DataFrame(np.random.randint(0, 2, (100, 1)), chunk_size=20)
classifier = LGBMClassifier(n_estimators=2)
classifier.fit(x, y)
```
```
KeyError                                  Traceback (most recent call last)
/home/admin/work/_public-mars-0.5.5.zip/mars/scheduler/graph.py in _execute_graph()

/home/admin/work/_public-mars-0.5.5.zip/mars/utils.py in _wrapped()

/home/admin/work/_public-mars-0.5.5.zip/mars/utils.py in _inner()

/home/admin/work/_public-mars-0.5.5.zip/mars/scheduler/graph.py in prepare_graph()

/home/admin/work/_public-mars-0.5.5.zip/mars/utils.py in _inner()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in build()

/home/admin/work/_public-mars-0.5.5.zip/mars/utils.py in _inner()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in build()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in inner()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in build()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in _tile()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in _tile()

/home/admin/work/_public-mars-0.5.5.zip/mars/scheduler/graph.py in on_tile()

/home/admin/work/_public-mars-0.5.5.zip/mars/context.py in h()

/home/admin/work/_public-mars-0.5.5.zip/mars/utils.py in _inner()

/home/admin/work/_public-mars-0.5.5.zip/mars/tiles.py in dispatch()

/home/admin/work/_public-mars-0.5.5.zip/mars/learn/contrib/lightgbm/_train.py in tile()

/home/admin/work/_public-mars-0.5.5.zip/mars/learn/contrib/lightgbm/_train.py in _concat_chunks_by_worker()

/home/admin/work/_public-mars-0.5.5.zip/mars/learn/utils/core.py in concat_chunks()

/home/admin/work/_public-mars-0.5.5.zip/mars/dataframe/operands.py in create_tileable_from_chunks()

/home/admin/work/_public-mars-0.5.5.zip/mars/dataframe/operands.py in _calc_dataframe_params()

/home/admin/work/_public-mars-0.5.5.zip/mars/dataframe/operands.py in <listcomp>()

KeyError: (1, 0)

The above exception was the direct cause of the following exception:

ExecutionFailed                           Traceback (most recent call last)
<ipython-input-41-9d4de811daf9> in <module>
----> 1 classifier.fit(x, y)

~/Documents/mars_dev/mars/mars/learn/contrib/lightgbm/classifier.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_sample_weight, eval_init_score, session, run_kwargs, **kwargs)
     30                           eval_sets=self._wrap_eval_tuples(eval_set, eval_sample_weight, eval_init_score),
     31                           model_type=LGBMModelType.CLASSIFIER,
---> 32                           session=session, run_kwargs=run_kwargs, **kwargs)
     33 
     34             self.set_params(**model.get_params())

~/Documents/mars_dev/mars/mars/learn/contrib/lightgbm/_train.py in train(params, train_set, eval_sets, **kwargs)
    348                    eval_weights=sample_weights[1:], eval_init_score=init_scores[1:],
    349                    model_type=model_type, timeout=timeout, lgbm_port=base_port, kwds=kwargs)
--> 350     ret = op().execute(session=session, **run_kwargs).fetch(session=session)
    351 
    352     bst = pickle.loads(ret)

~/Documents/mars_dev/mars/mars/core.py in execute(self, session, **kw)
    374             session.run(self, **kw)
    375             # return Tileable or ExecutableTuple itself
--> 376             return self
    377 
    378         if wait:

~/Documents/mars_dev/mars/mars/core.py in run()
    369         if session is None:
    370             session = Session.default_or_local()
--> 371 
    372         def run():
    373             # no more fetch, thus just fire run

~/Documents/mars_dev/mars/mars/session.py in run(self, *tileables, **kw)
    476         self._sess = RaySession(**kwargs)
    477 
--> 478     def __getstate__(self):
    479         return self._endpoint, self._kws, self.session_id, self._backend
    480 

~/Documents/mars_dev/mars/mars/web/session.py in run(self, *tileables, **kw)
    212             timeout_val = min(check_interval, timeout - time_elapsed) if timeout > 0 else check_interval
    213             try:
--> 214                 if self._check_response_finished(graph_url, timeout_val):
    215                     break
    216             except KeyboardInterrupt:

~/Documents/mars_dev/mars/mars/web/session.py in _check_response_finished(self, graph_url, timeout)
    172                 exc_info = pickle.loads(base64.b64decode(resp_json['exc_info']))
    173                 exc = exc_info[1].with_traceback(exc_info[2])
--> 174                 raise ExecutionFailed('Graph execution failed.') from exc
    175             else:
    176                 raise ExecutionFailed('Graph execution failed with unknown reason.')

ExecutionFailed: 'Graph execution failed.'
```

**Comment by wjsi** [comment]
Same issue for XGBoost.
