### ISSUE TITLE
[BUG] Silent subprocess if main process quit normally

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#1785]
**Describe the bug**

For now, if main process quit normally, subprocess will raise quite a few errors due to broken pipe.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version
2. The version of Mars you use
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.
5. Minimized code to reproduce the error.

Error message includes:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 1329, in mars.actors.pool.gevent_pool.Dispatcher.on_receive
  File "mars/actors/pool/gevent_pool.pyx", line 1333, in mars.actors.pool.gevent_pool.Dispatcher.on_receive
  File "mars/actors/pool/gevent_pool.pyx", line 1292, in mars.actors.pool.gevent_pool.Dispatcher._on_receive_result
  File "mars/actors/pool/gevent_pool.pyx", line 1309, in mars.actors.pool.gevent_pool.Dispatcher._on_receive_result
AttributeError: 'NoneType' object has no attribute 'put'
2020-12-15T03:08:43Z <Greenlet at 0x7f64ca06c950: <built-in method on_receive of mars.actors.pool.gevent_pool.Dispatcher object at 0x7f64cd0ea750>(b'\x03\x01 \x00\x00\x00\x00\x00\x00\x00\xf4%\xe7$\)> failed with AttributeError
```

**Comment by qinxuye** [comment]
This issue should be addressed in Project Galois.
