### ISSUE TITLE
[BUG] concat Series with DataFrame or Series Failed

### ISSUE THREAD

**Issue by smartguo** [mars-project/mars#1796]
**Describe the bug**
concat Series with DataFrame or Series Failed.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.8.3
2. The version of Mars you use: pymars[distributed]==0.6.0
3. Versions of crucial packages, such as numpy, scipy and protobuf: numpy==1.19.4, scipy==1.5.4, protobuf==3.14.0, pyarrow==2.0.0
4. Minimized code and full stack of the error.
concat dataframe with series shown as below:
```python
import mars.dataframe as md
df = md.read_parquet("data.parquet")
df.execute()
md.concat([df[["id", "var_1"]], df["var_0"]], axis=1).execute()
```
```bash
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    md.concat([df["var_0"], df[["id", "var_1"]]], axis=1).execute()
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/merge/concat.py", line 476, in concat
    return op(objs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/merge/concat.py", line 399, in __call__
    return self._call_dataframes(objs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/merge/concat.py", line 380, in _call_dataframes
    col_length += df.shape[1]
IndexError: tuple index out of range
```
concat series with series shown as below
```python
import mars.dataframe as md
df = md.read_parquet("data.parquet")
df.execute()
print(md.concat([df["id"], df["var_0"]], axis=1).execute())
```
```bash
Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    print(md.concat([df["id"], df["var_0"]], axis=1).execute())
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/core.py", line 131, in __str__
    return self._data.__str__()
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/core.py", line 1083, in __str__
    return self._to_str(representation=False)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/core.py", line 1058, in _to_str
    corner_data = fetch_corner_data(
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/utils.py", line 899, in fetch_corner_data
    ExecutableTuple([head, tail]).fetch(session=session)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/core.py", line 738, in fetch
    return super().fetch(session=session, **kw)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/core.py", line 408, in fetch
    return session.fetch(self, **kw)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/session.py", line 528, in fetch
    result = self._sess.fetch(*tileables, **kw)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/session.py", line 125, in fetch
    return self._executor.fetch_tileables(tileables, **kw)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/executor.py", line 973, in fetch_tileables
    result = self.execute_tileables(tileables, **kw)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/executor.py", line 860, in execute_tileables
    chunk_graph = chunk_graph_builder.build(
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 347, in build
    chunk_graph = super().build(
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 262, in build
    self._on_tile_failure(tileable_data.op, exc_info)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 301, in inner
    raise exc_info[1].with_traceback(exc_info[2]) from None
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 242, in build
    tiled = self._tile(tileable_data, tileable_graph)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 337, in _tile
    return super()._tile(tileable_data, tileable_graph)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 201, in _tile
    tds[0]._inplace_tile()
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/core.py", line 168, in _inplace_tile
    return handler.inplace_tile(self)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 136, in inplace_tile
    dispatched = self.dispatch(to_tile.op)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tiles.py", line 119, in dispatch
    tiled = op_cls.tile(op)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/indexing/iloc.py", line 344, in tile
    return [handler.handle(op)]
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tensor/indexing/index_lib.py", line 898, in handle
    self._process(context, index_infos)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tensor/indexing/index_lib.py", line 918, in _process
    index_info.handler.process(index_info, context)
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/tensor/indexing/index_lib.py", line 331, in process
    self.set_chunk_index_info(context, index_info, chunk_index, chunk_index_info,
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/dataframe/indexing/index_lib.py", line 178, in set_chunk_index_info
    index = chunk_input.columns_value.to_pandas()
  File "/home/smartguo/lib/anaconda3/lib/python3.8/site-packages/mars/core.py", line 171, in __getattr__
    return getattr(self._data, attr)
AttributeError: 'SeriesChunkData' object has no attribute 'columns_value'
```

**Expected behavior**
concat series with dataframe or series and return a dataframe

**Comment by qinxuye** [comment]
Thank you for your report, will fix it ASAP.
