### ISSUE TITLE
[BUG] execute required before follow-up operation when using tensor

### ISSUE THREAD

**Issue by smartguo** [mars-project/mars#1843]
**Describe the bug**
execute required before follow-up operation when using tensor

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.7.9
2. The version of Mars you use: build on `master 1b3801a`
3. Versions of crucial packages, such as numpy, scipy and protobuf: numpy==1.19.4, scipy==1.5.4, protobuf==3.14.0, pyarrow==2.0.0
4. Minimized code and full stack of the error.
```python
import mars.dataframe as md
import mars.tensor as mt
from mars.learn.contrib import xgboost as xgb

model = xgb.XGBClassifier()
model.load_model('var_40.model')

df = md.read_parquet('var_40.parquet')
tensor_var = df.iloc[:,1:].astype(float).to_tensor()
score = model.predict_proba(tensor_var, run=False)
# uncomment the line below or drop run=False above will work
# print(score.execute())
df_res = md.DataFrame(score, columns=["probability"])
df_res.to_parquet("result-*.parquet",index=False).execute()
```
```
Traceback (most recent call last):
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/pandas/core/dtypes/common.py", line 171, in ensure_python_int
    new_value = int(value)
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tensor_loop.py", line 14, in <module>
    df_res = md.DataFrame(score, columns=["probability"])
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/dataframe/initializer.py", line 47, in __init__
    df = dataframe_from_tensor(data, index=index, columns=columns, gpu=gpu, sparse=sparse)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/dataframe/datasource/from_tensor.py", line 357, in dataframe_from_tensor
    return op(tensor, index, columns)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/utils.py", line 451, in _inner
    return func(*args, **kwargs)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/dataframe/datasource/from_tensor.py", line 83, in __call__
    return self._call_input_tensor(input_tensor, index, columns)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/dataframe/datasource/from_tensor.py", line 156, in _call_input_tensor
    index_value = parse_index(pd.RangeIndex(start=0, stop=input_tensor.shape[0]))
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/pandas/core/indexes/range.py", line 107, in __new__
    stop = ensure_python_int(stop)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/pandas/core/dtypes/common.py", line 174, in ensure_python_int
    raise TypeError(f"Wrong type {type(value)} for value {value}") from err
TypeError: Wrong type <class 'float'> for value nan
```
```python
import mars.dataframe as md
import mars.tensor as mt
from mars.learn.contrib import xgboost as xgb

model = xgb.XGBClassifier()
model.load_model('var_40.model')
df = md.read_parquet('var_40.parquet')
tensor_id = df.iloc[:, 0:1].to_tensor()
# uncomment the line below will work, with or without run=False has no effect
# print(tensor_id.execute())
tensor_var = df.iloc[:, 1:].to_tensor()

score = model.predict_proba(tensor_var,run=False).reshape(-1, 1)
ts_res = mt.concatenate([tensor_id, score], axis=1)
df_res = md.DataFrame(ts_res, columns=["id", "score"])
df_res.to_parquet("result-*.parquet").execute()
```
```
Traceback (most recent call last):
  File "demo_tensor.py", line 15, in <module>
    score = model.predict_proba(tensor_var,run=False).reshape(-1, 1)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/tensor/core.py", line 269, in reshape
    return reshape(self, shape, order=order)
  File "/home/smartguo/lib/anaconda3/envs/mars/lib/python3.7/site-packages/mars/tensor/reshape/reshape.py", line 504, in reshape
    raise ValueError(f'tensor shape is unknown, {a.shape}')
ValueError: tensor shape is unknown, (nan,)
```

**Expected behavior**
Just one execute operation at the end without explicitly adding other execute().

**Comment by qinxuye** [comment]
Thank you for your report, will fix it ASAP.
