### ISSUE TITLE
[BUG] Version of numpy should be fixed when building wheels

### ISSUE THREAD

**Issue by wjsi** [mars-project/mars#197]
**Describe the bug**
As numpy may [change their API version](https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst#c-api-changes), we should fix the version of numpy as the version used by pyarrow.

**Comment by chineking** [comment]
Currently, our version of 0.1.0 and 0.2.0a1 are built on numpy 1.16, but conda's latest version is 1.15.4, if we install latest pymars, and run the scheduler, the error is:

```
Traceback (most recent call last):
  File "/home/xuye.qin/miniconda3/bin/mars-scheduler", line 7, in <module>
    from mars.scheduler.__main__ import main
  File "/home/xuye.qin/miniconda3/lib/python3.7/site-packages/mars/scheduler/__init__.py", line 16, in <module>
    from .graph import GraphActor, GraphMetaActor
  File "/home/xuye.qin/miniconda3/lib/python3.7/site-packages/mars/scheduler/graph.py", line 29, in <module>
    from ..graph import DAG
  File "mars/serialize/core.pxd", line 44, in init mars.graph
  File "/home/xuye.qin/miniconda3/lib/python3.7/site-packages/mars/serialize/__init__.py", line 25, in <module>
    from .jsonserializer import JsonSerializeProvider
  File "__init__.pxd", line 918, in init mars.serialize.jsonserializer
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
