### ISSUE TITLE
Execution error  zmc1_h_21 = mt.where(self.high_array >= 21, 1, 0).execute()

### ISSUE THREAD

**Issue by shizhiqiang007** [mars-project/mars#2009]
The execution reported the following error, I don’t know what caused it 
error:
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by qinxuye** [comment]
Could you please provide complete code snippet as well as full error stack please?

**Comment by shizhiqiang007** [comment]
> Could you please provide minimal code snippet that can reproduce this error as well as full error stack please?

mt.where(self.high_array >= 39, 1, 0).execute()
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-00829d36cbac>", line 1, in <module>
    mt.where(self.high_array >= 39, 1, 0).execute()
  File "/usr/local/python3/lib/python3.6/site-packages/mars/core.py", line 646, in execute
    return run()
  File "/usr/local/python3/lib/python3.6/site-packages/mars/core.py", line 642, in run
    self.data.execute(session, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/core.py", line 379, in execute
    return run()
  File "/usr/local/python3/lib/python3.6/site-packages/mars/core.py", line 374, in run
    session.run(self, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/session.py", line 499, in run
    result = self._sess.run(*tileables, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/session.py", line 108, in run
    res = self._executor.execute_tileables(tileables, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/utils.py", line 457, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/executor.py", line 891, in execute_tileables
    tileable_graph, chunk_result, chunk_graph_builder.interrupted_ops)
  File "/usr/local/python3/lib/python3.6/site-packages/mars/executor.py", line 750, in _update_tileable_and_chunk_shape
    if has_unknown_shape(tiled_n):
  File "/usr/local/python3/lib/python3.6/site-packages/mars/utils.py", line 722, in has_unknown_shape
    if any(np.isnan(s) for s in itertools.chain(*tiled.nsplits)):
  File "/usr/local/python3/lib/python3.6/site-packages/mars/utils.py", line 722, in <genexpr>
    if any(np.isnan(s) for s in itertools.chain(*tiled.nsplits)):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by qinxuye** [comment]
How about a minimal code snippet to help us to reproduce the error?

**Comment by shizhiqiang007** [comment]
> How about a minimal code snippet to help us to reproduce the error?

This is the complete code, run directly to reproduce the error，I just tried to change to the numpy code and no error will be reported

import mars.tensor as mt
x = mt.arange(9.).reshape(3, 3)
mt.where(x < 5, 2, -1).execute()

**Comment by qinxuye** [comment]
> > How about a minimal code snippet to help us to reproduce the error?
> 
> This is the complete code, run directly to reproduce the error，I just tried to change to the numpy code and no error will be reported
> 
> import mars.tensor as mt
> x = mt.arange(9.).reshape(3, 3)
> mt.where(x < 5, 2, -1).execute()

Thank you, I can reproduce the error, it will be fixed ASAP.
