### ISSUE TITLE
[BUG] mt.where() Found that there are still problems with some data

### ISSUE THREAD

**Issue by shizhiqiang007** [mars-project/mars#2043]
```python
self.l2r_arr
Out[16]: 
array([[1.8e+02, 1.8e+02, 4.0e+02, 4.0e+02, 1.6e+02, 1.0e-02],
       [1.8e+02, 1.8e+02, 4.0e+02, 4.0e+02, 1.6e+02, 1.0e-02],
       [1.8e+02, 1.8e+02, 4.0e+02, 4.0e+02, 1.6e+02, 1.0e-02],
       ...,
       [2.6e+02, 1.2e+02, 3.8e+02, 4.0e+02, 1.6e+02, 1.0e-02],
       [2.6e+02, 1.2e+02, 3.8e+02, 4.0e+02, 1.6e+02, 1.0e-02],
       [2.6e+02, 1.2e+02, 3.8e+02, 4.0e+02, 1.6e+02, 1.0e-02]])


mt.where(self.l2r_arr <= 0, 0.01, self.l2r_arr)
```

```
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-59f7f69c3674>", line 1, in <module>
    mt.where(self.l2r_arr <= 0, 0.01, self.l2r_arr)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/base/where.py", line 182, in where
    return op(condition, x, y, shape=shape)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/utils.py", line 460, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/base/where.py", line 63, in __call__
    return self.new_tensor([condition, x, y], shape)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/operands.py", line 34, in new_tensor
    return self.new_tensors(inputs, shape=shape, dtype=dtype, order=order, **kw)[0]
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/operands.py", line 29, in new_tensors
    output_limit=output_limit, kws=kws, dtype=dtype, order=order, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/operands.py", line 455, in new_tileables
    ExecutableTuple(tileables).execute(fetch=False)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/core.py", line 770, in execute
    return super().execute(session=session, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/core.py", line 383, in execute
    return run()
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/core.py", line 378, in run
    session.run(self, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/session.py", line 506, in run
    result = self._sess.run(*tileables, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/session.py", line 111, in run
    res = self._executor.execute_tileables(tileables, **kw)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/utils.py", line 460, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/executor.py", line 866, in execute_tileables
    tileables, tileable_graph=tileable_graph)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/utils.py", line 460, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 348, in build
    tileables, tileable_graph=tileable_graph)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/utils.py", line 460, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 262, in build
    self._on_tile_failure(tileable_data.op, exc_info)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 301, in inner
    raise exc_info[1].with_traceback(exc_info[2]) from None
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 242, in build
    tiled = self._tile(tileable_data, tileable_graph)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 337, in _tile
    return super()._tile(tileable_data, tileable_graph)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 201, in _tile
    tds[0]._inplace_tile()
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/core.py", line 169, in _inplace_tile
    return handler.inplace_tile(self)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 136, in inplace_tile
    dispatched = self.dispatch(to_tile.op)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/utils.py", line 460, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tiles.py", line 119, in dispatch
    tiled = op_cls.tile(op)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/base/where.py", line 68, in tile
    inputs = unify_chunks(*[(input, list(range(input.ndim))[::-1]) for input in op.inputs])
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/utils.py", line 495, in unify_chunks
    return unify_nsplits(*tensor_axes)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/utils.py", line 483, in unify_nsplits
    res.append(t.rechunk(new_chunk)._inplace_tile())
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/rechunk/rechunk.py", line 104, in rechunk
    chunk_size = get_nsplits(tensor, chunk_size, tensor.dtype.itemsize)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/rechunk/core.py", line 38, in get_nsplits
    return decide_chunk_sizes(tileable.shape, chunk_size, itemsize)
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/utils.py", line 560, in decide_chunk_sizes
    return normalize_chunk_sizes(shape, tuple(chunk_size[j] for j in range(len(shape))))
  File "/usr/local/python3/lib/python3.6/site-packages/pymars-0.7.0a7-py3.6-linux-x86_64.egg/mars/tensor/utils.py", line 66, in normalize_chunk_sizes
    raise ValueError('chunks shape should be of the same length, '
ValueError: chunks shape should be of the same length, got shape: 7, chunks: (6,)
```

**Comment by wjsi** [comment]
Please provide minimal code reproducing this error stack.

**Comment by shizhiqiang007** [comment]
> Please provide minimal code reproducing this error stack.

I probably know the problem. I found that it was the problem. I first deleted a column and then inserted a column. I found that it was not inserted, but the shape changed.

>>> import mars.tensor as mt
>>> a = mt.array([[1, 1], [2, 2], [3, 3]])
>>> last_point = a[:,0]
>>> b = mt.delete(a, 0, axis=1)
>>> b
Tensor <op=TensorDelete, shape=(3, 1), key=d03e14c3791cbe24e0421270ec46501c>
>>> b.execute()
array([[1],
       [2],
       [3]])
>>> b = mt.insert(b, a.shape[1] - 1, values=last_point, axis=1)
>>> b
Tensor <op=TensorInsert, shape=(3, 2), key=8355d492230319f87ee50622b12807b4>
>>> b.execute()
array([[1],
       [2],
       [3]])
>>> b.shape()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'tuple' object is not callable
>>> b.execute()
array([[1],
       [2],
       [3]])
>>> b.execute().shape
(3, 2)
>>> last_point
Tensor <op=TensorIndex, shape=(3,), key=21be4b37db8a06fd8e62257c49abbf3b>
>>> last_point.execute()
array([1, 2, 3])

**Comment by qinxuye** [comment]
Thank you for your feedback, will fix it ASAP, cc @hekaisheng .
