### ISSUE TITLE
[BUG] PCA runs failed in cluster mode

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#2091]
**Describe the bug**
Created a Mars cluster and ran the PCA example, it failed with `AttributeError`:
``` Python
In [9]: from mars.learn.datasets import make_blobs 
   ...: from mars.learn.decomposition import PCA 
   ...: X, y = make_blobs( 
   ...:     n_samples=100000, n_features=3, 
   ...:     centers=[[3, 3, 3], [0, 0, 0], 
   ...:               [1, 1, 1], [2, 2, 2]], 
   ...:     cluster_std=[0.2, 0.1, 0.2, 0.2], 
   ...:     random_state=9) 
   ...: pca = PCA(n_components=3) 
   ...: pca.fit(X) 
   ...: print(pca.explained_variance_ratio_) 
   ...: print(pca.explained_variance_)                                                              
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/admin/work/_public-mars-0.6.7.zip/mars/scheduler/graph.py in _execute_graph()

/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py in _wrapped()

/home/admin/work/_public-mars-0.6.7.zip/mars/scheduler/graph.py in create_operand_actors()

/opt/conda/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.result()

/opt/conda/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

/opt/conda/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

/opt/conda/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult.get()

/opt/conda/lib/python3.7/site-packages/gevent/_gevent_cevent.cpython-37m-x86_64-linux-gnu.so in gevent._gevent_cevent.AsyncResult._raise_exception()

/opt/conda/lib/python3.7/site-packages/gevent/_compat.py in reraise()

/opt/conda/lib/python3.7/site-packages/gevent/threadpool.py in __run_task()

~/Documents/mars_dev/mars/mars/actors/pool/gevent_pool.pyx in mars.actors.pool.gevent_pool.GeventThreadPool._wrap_watch.inner()
    200             greenlet = gevent.spawn(check, event)
--> 201             result = fn(*args, **kwargs)
    202             event.set()

/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py in _wrapped()

/home/admin/work/_public-mars-0.6.7.zip/mars/scheduler/graph.py in get_executable_operand_dag()

/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py in build_fetch_chunk()

/home/admin/work/_public-mars-0.6.7.zip/mars/tensor/core.py in params()

/home/admin/work/_public-mars-0.6.7.zip/mars/tensor/core.py in dtype()

AttributeError: 'LearnShuffleProxy' object has no attribute 'dtype'

The above exception was the direct cause of the following exception:

ExecutionFailed                           Traceback (most recent call last)
<ipython-input-9-b71fabe93a66> in <module>
      8     random_state=9)
      9 pca = PCA(n_components=3)
---> 10 pca.fit(X)
     11 print(pca.explained_variance_ratio_)
     12 print(pca.explained_variance_)

~/Documents/mars_dev/mars/mars/learn/decomposition/_pca.py in fit(self, X, y, session, run_kwargs)
    339             Returns the instance itself.
    340         """
--> 341         self._fit(X, session=session, run=True, run_kwargs=run_kwargs)
    342         return self
    343 

~/Documents/mars_dev/mars/mars/learn/decomposition/_pca.py in _fit(self, X, session, run, run_kwargs)
    424 
    425         if run:
--> 426             self._run(ret, session=session, run_kwargs=run_kwargs)
    427         return ret
    428 

~/Documents/mars_dev/mars/mars/learn/decomposition/_pca.py in _run(self, result, session, run_kwargs)
    380         to_run_tensors.append(self.singular_values_)
    381 
--> 382         ExecutableTuple(to_run_tensors).execute(session=session, **(run_kwargs or {}))
    383 
    384     def _fit(self, X, session=None, run=True, run_kwargs=None):

~/Documents/mars_dev/mars/mars/core.py in execute(self, session, **kw)
    762         if len(self) == 0:
    763             return self
--> 764         return super().execute(session=session, **kw)
    765 
    766     def fetch(self, session=None, **kw):

~/Documents/mars_dev/mars/mars/core.py in execute(self, session, **kw)
    377 
    378         if wait:
--> 379             return run()
    380         else:
    381             # leverage ThreadPoolExecutor to submit task,

~/Documents/mars_dev/mars/mars/core.py in run()
    372         def run():
    373             # no more fetch, thus just fire run
--> 374             session.run(self, **kw)
    375             # return Tileable or ExecutableTuple itself
    376             return self

~/Documents/mars_dev/mars/mars/session.py in run(self, *tileables, **kw)
    498         tileables = tuple(mt.tensor(t) if not isinstance(t, (Entity, Base)) else t
    499                           for t in tileables)
--> 500         result = self._sess.run(*tileables, **kw)
    501 
    502         for t in tileables:

~/Documents/mars_dev/mars/mars/web/session.py in run(self, *tileables, **kw)
    214                 timeout_val = min(check_interval, timeout - time_elapsed) if timeout > 0 else check_interval
    215                 try:
--> 216                     if self._check_response_finished(graph_url, timeout_val):
    217                         break
    218                 except KeyboardInterrupt:

~/Documents/mars_dev/mars/mars/web/session.py in _check_response_finished(self, graph_url, timeout)
    173                 exc_info = pickle.loads(base64.b64decode(resp_json['exc_info']))
    174                 exc = exc_info[1].with_traceback(exc_info[2])
--> 175                 raise ExecutionFailed('Graph execution failed.') from exc
    176             else:
    177                 raise ExecutionFailed('Graph execution failed with unknown reason.')

ExecutionFailed: 'Graph execution failed.'

```

the error on the server side is:
```
Traceback (most recent call last):
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py", line 384, in _wrapped
    return func(*args, **kwargs)
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/scheduler/graph.py", line 946, in create_operand_actors
    self.get_executable_operand_dag, op_key).result()
  File "src/gevent/event.py", line 383, in gevent._gevent_cevent.AsyncResult.result
  File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/opt/conda/lib/python3.7/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/gevent/threadpool.py", line 142, in __run_task
    thread_result.set(func(*args, **kwargs))
  File "mars/actors/pool/gevent_pool.pyx", line 201, in mars.actors.pool.gevent_pool.GeventThreadPool._wrap_watch.inner
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py", line 384, in _wrapped
    return func(*args, **kwargs)
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/scheduler/graph.py", line 833, in get_executable_operand_dag
    = build_fetch_chunk(inp, input_chunk_keys).data
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/utils.py", line 574, in build_fetch_chunk
    params = chunk.params.copy()
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/tensor/core.py", line 78, in params
    'dtype': self.dtype,
  File "/home/admin/work/_public-mars-0.6.7.zip/mars/tensor/core.py", line 105, in dtype
    return getattr(self, '_dtype', None) or self.op.dtype
AttributeError: 'LearnShuffleProxy' object has no attribute 'dtype'
```

**Comment by wjsi** [comment]
The actual cause is that in ``LearnShuffle`` invoked in `make_blobs`, `dtype` attribute is not specified.
