### ISSUE TITLE
[BUG] Can't execute tensor directly

### ISSUE THREAD

**Issue by chaokunyang** [mars-project/mars#2119]
**Describe the bug**
Can't execute tensor directly

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version 3.8
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and pandas: latest
4. Full stack of the error.
```
Traceback (most recent call last):
  File "/tmp/test.py", line 48, in <module>
    main(*sys.argv[1:])
  File "/tmp/test.py", line 23, in main
    test_driver(client.web_address)
  File "/tmp/test.py", line 32, in test_driver
    print(c.execute())   # fail
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/entity/tileables.py", line 470, in execute
    result = self.data.execute(session=session, **kw)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/entity/executable.py", line 110, in execute
    return self._execute(session=session, **kw)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/entity/executable.py", line 100, in _execute
    return execute(self, session=session, wait=wait, **kw)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/session.py", line 57, in inner
    result, default_session_in_thread = fut.result()
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/session.py", line 54, in run_in_thread
    return func(*args, **kwargs), get_default_session()
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/session.py", line 375, in execute
    _loop.run_until_complete(_execute(
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/session.py", line 346, in _execute
    await execution_info
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/session.py", line 330, in _attach_session
    fut.result()
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/deploy/oscar/session.py", line 127, in _run_in_background
    self._tileable_to_fetch[tileable] = fetch_tileable
  File "/Users/chaokunyang/.pyenv/versions/3.8.1/lib/python3.8/weakref.py", line 396, in __setitem__
    self.data[ref(key, self._remove)] = value
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/tensor/core.py", line 336, in __len__
    return len(self._data)
  File "/Users/chaokunyang/ant/Development/DevProjects/python/mars/mars/core/entity/tileables.py", line 425, in __len__
    raise TypeError('len() of unsized object')
TypeError: len() of unsized object

```
5. Minimized code to reproduce the error.
```
import asyncio
import logging
import ray
import sys
import time
from mars.deploy.oscar.ray import new_cluster
from mars.services.session.api import OscarSessionAPI
import numpy as np
import mars.tensor as mt
import mars.deploy.oscar.session  # register oscar session class
from mars.core.session import new_session
from mars.serialization.ray import register_ray_serializers

logger = logging.getLogger(__name__)


def main(*args):
    print(f"args {args}")
    logging.basicConfig(format=ray.ray_constants.LOGGER_FORMAT, level=logging.INFO)
    cluster_name = 'mars_cluster_' + str(int(time.time()))
    client = asyncio.new_event_loop().run_until_complete(
        new_cluster(cluster_name, worker_num=1, worker_cpu=1, worker_mem=0))
    test_driver(client.web_address)


def test_driver(web_address):
    register_ray_serializers()
    session = new_session(web_address, backend='oscar', default=True)
    raw = np.random.RandomState(0).rand(1000, 5)
    c = mt.tensor(raw, chunk_size=500).sum()
    print(session.execute(c))
    print(c.execute())   # fail
    print("Execution succeed.")


if __name__ == '__main__':
    try:
        from ray.cluster_utils import Cluster
    except ModuleNotFoundError:
        from ray._private.cluster_utils import Cluster
    cluster = Cluster()
    remote_nodes = []
    num_nodes = 1
    for i in range(num_nodes):
        remote_nodes.append(cluster.add_node(num_cpus=20))
        if len(remote_nodes) == 1:
            ray.init(address=cluster.address)
    main(*sys.argv[1:])

```

**Comment by qinxuye** [comment]
I ran the code based on the master branch, seems issue does not show any more, will close it first, feel free to reopen if issue stays still.
