### ISSUE TITLE
[BUG] Mars with ray cluster went into KeyError when executing jobs

### ISSUE THREAD

**Issue by keyile** [mars-project/mars#2180]
**Describe the bug**
With `new_cluster` in `mars.deploy.oscar.ray`, the session.execute sometimes terminates with a KeyError.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: 3.8.10
2. The version of Mars you use: latest master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
```
Traceback (most recent call last):
  File "/Users/admin/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py", line 29, in <module>
    asyncio.run(main())
  File "/Users/admin/.pyenv/versions/3.8.10/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/admin/.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/admin/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch.py", line 25, in main
    await info
  File "/Users/admin/mars/mars/deploy/oscar/session.py", line 160, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/Users/admin/mars/mars/services/scheduling/utils.py", line 33, in redirect_subtask_errors
    yield
  File "/Users/admin/mars/mars/services/scheduling/supervisor/queueing.py", line 146, in submit_subtasks
    submitted_ids = set(await self._slots_ref.apply_subtask_slots(
  File "/Users/admin/mars/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/Users/admin/mars/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/Users/admin/mars/mars/oscar/backends/pool.py", line 490, in send
    result = await future
  File "/Users/admin/mars/mars/oscar/api.py", line 111, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 333, in __on_receive__
  File "mars/oscar/core.pyx", line 311, in mars.oscar.core._Actor.__on_receive__
  File "mars/oscar/core.pyx", line 314, in mars.oscar.core._Actor.__on_receive__
  File "/Users/admin/mars/mars/services/scheduling/supervisor/globalslot.py", line 61, in apply_subtask_slots
    total_slots = self._band_total_slots[band]
KeyError: ('ray://test_cluster/0/1', 'numa-0')
```
5. Minimized code to reproduce the error.
```
async def main():
    ray.init(num_cpus=12, num_gpus=2)

    client = await new_cluster('test_cluster',
                               worker_num=2,
                               worker_cpu=2,
                               worker_mem=1 * 1024 ** 3  # not used now
                               )

    s = np.random.RandomState(0)
    raw = pd.DataFrame(s.rand(100, 4), columns=list('abcd'))
    df = md.DataFrame(raw, chunk_size=30)
    r = df.describe()
    info = await client.session.execute(r)
    await info


if __name__ == '__main__':
    asyncio.run(main())
```
The test_ray.py also has the same problem.

**Expected behavior**
The program is then terminated.  This behavior is kind of random.

**Comment by qinxuye** [comment]
Are you interested in solving this issue?
