### ISSUE TITLE
[BUG] groupby with shuffle method failed

### ISSUE THREAD

**Issue by qinxuye** [mars-project/mars#2200]
**Describe the bug**

`groupby` with shuffle method failed.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version
2. The version of Mars you use
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
5. Minimized code to reproduce the error.

```
In [7]: %%time
   ...: df = md.read_csv(f'{data_name}.csv')
   ...: df.groupby(['id1','id2','id3','id4','id5','id6'],  sort=False, as_index=False).agg({'v3':'sum', 'v1':'size'}, method='shuffle').execute()
   ...: 
   ...: 
 47%|██████████████████████████████████████████████████████████████████████▌                                                                               | 47.058823529411754/100 [00:11<00:08,  6.09it/s]Exception in callback _execute.<locals>._attach_session(<Task finishe...ty sequence')>) at /Users/qinxuye/Workspace/mars/mars/core/session.py:611
handle: <Handle _execute.<locals>._attach_session(<Task finishe...ty sequence')>) at /Users/qinxuye/Workspace/mars/mars/core/session.py:611>
Traceback (most recent call last):
  File "/Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/qinxuye/Workspace/mars/mars/core/session.py", line 612, in _attach_session
    fut.result()
  File "/Users/qinxuye/Workspace/mars/mars/deploy/oscar/session.py", line 160, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/utils.py", line 33, in redirect_subtask_errors
    yield
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/manager.py", line 80, in add_subtasks
    await self._queueing_ref.add_subtasks(
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/pool.py", line 492, in send
    result = await future
  File "/Users/qinxuye/Workspace/mars/mars/oscar/api.py", line 111, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 333, in __on_receive__
  File "mars/oscar/core.pyx", line 311, in mars.oscar.core._Actor.__on_receive__
  File "mars/oscar/core.pyx", line 314, in mars.oscar.core._Actor.__on_receive__
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/queueing.py", line 108, in add_subtasks
    bands = await self._assigner_ref.assign_subtasks(subtasks)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/pool.py", line 492, in send
    result = await future
  File "/Users/qinxuye/Workspace/mars/mars/oscar/api.py", line 111, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 333, in __on_receive__
  File "mars/oscar/core.pyx", line 311, in mars.oscar.core._Actor.__on_receive__
  File "mars/oscar/core.pyx", line 314, in mars.oscar.core._Actor.__on_receive__
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/assigner.py", line 72, in assign_subtasks
    selected_bands[subtask.subtask_id] = [random.choice(self._bands)]
  File "/Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
Task exception was never retrieved
future: <Task finished name='Task-820' coro=<_wrap_awaitable() done, defined at /Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/asyncio/tasks.py:677> exception=IndexError('Cannot choose from an empty sequence')>
Traceback (most recent call last):
  File "/Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/qinxuye/Workspace/mars/mars/core/session.py", line 612, in _attach_session
    fut.result()
  File "/Users/qinxuye/Workspace/mars/mars/deploy/oscar/session.py", line 160, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/utils.py", line 33, in redirect_subtask_errors
    yield
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/manager.py", line 80, in add_subtasks
    await self._queueing_ref.add_subtasks(
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/pool.py", line 492, in send
    result = await future
  File "/Users/qinxuye/Workspace/mars/mars/oscar/api.py", line 111, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 333, in __on_receive__
  File "mars/oscar/core.pyx", line 311, in mars.oscar.core._Actor.__on_receive__
  File "mars/oscar/core.pyx", line 314, in mars.oscar.core._Actor.__on_receive__
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/queueing.py", line 108, in add_subtasks
    bands = await self._assigner_ref.assign_subtasks(subtasks)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/Users/qinxuye/Workspace/mars/mars/oscar/backends/pool.py", line 492, in send
    result = await future
  File "/Users/qinxuye/Workspace/mars/mars/oscar/api.py", line 111, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 333, in __on_receive__
  File "mars/oscar/core.pyx", line 311, in mars.oscar.core._Actor.__on_receive__
  File "mars/oscar/core.pyx", line 314, in mars.oscar.core._Actor.__on_receive__
  File "/Users/qinxuye/Workspace/mars/mars/services/scheduling/supervisor/assigner.py", line 72, in assign_subtasks
    selected_bands[subtask.subtask_id] = [random.choice(self._bands)]
  File "/Users/qinxuye/miniconda3/envs/mars3.8/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by qinxuye** [comment]
Resolved by #2205 .
