### ISSUE TITLE
[BUG]Pip installation problem

### ISSUE THREAD

**Issue by SunYanCN** [mars-project/mars#231]
**Describe the bug**
Install the latest mars, you should upgrade the numpy version to 1.16.0rc2, otherwise you will get an error.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Python==3.6.5
2. Mars==0.2.0a1
3 .numpy<=1.15.4
4. Full stack of the error.
```Traceback (most recent call last):
  File "/home/sunyan/PycharmProjects/TT/4.py", line 39, in <module>
    import mars.tensor as mt
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/tensor/__init__.py", line 18, in <module>
    from .expressions.datasource import tensor, array, asarray, scalar, \
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/tensor/expressions/__init__.py", line 17, in <module>
    from . import rechunk
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/tensor/expressions/rechunk/__init__.py", line 17, in <module>
    from .rechunk import rechunk
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/tensor/expressions/rechunk/rechunk.py", line 26, in <module>
    from ....operands import Rechunk
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/operands/__init__.py", line 18, in <module>
    from .core import *
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/operands/core.py", line 20, in <module>
    from ..serialize import SerializableMetaclass, ValueType, ProviderType, \
  File "/home/sunyan/anaconda3/lib/python3.6/site-packages/mars/serialize/__init__.py", line 25, in <module>
    from .jsonserializer import JsonSerializeProvider
  File "__init__.pxd", line 918, in init mars.serialize.jsonserializer
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject```
5. Minimized code to reproduce the error.
`import mars.tensor as mt`

**Comment by wjsi** [comment]
Duplicate with #197 and will be solved in the next release. Caused by upgrade in numpy api version. Upgrading to numpy>=1.15 will solve this issue.

**Comment by chineking** [comment]
The next releases of Mars will no longer requires the version of Numpy, thanks for your feedback.
