### ISSUE TITLE
[BUG] When using groupby and agg, shows cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by ZYLi24** [mars-project/mars#2431]
**Describe the bug**
When I try to use groupby and then put a function in agg(), it will show cannot pickle 'weakref' object.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version - 3.8

2. The version of Mars you use - 0.7.2

3. Versions of crucial packages, such as numpy, scipy and pandas

4. Full stack of the error.

TypeError: cannot pickle 'weakref' object

5. Minimized code to reproduce the error.

```
df = md.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                   columns=['a','b','c'])
df.groupby('a')['c'].agg(lambda x: mt.sum(x))

100%|██████████| 100.0/100 [00:00<00:00, 7432.89it/s]
100%|██████████| 100.0/100 [00:00<00:00, 6825.56it/s]
100%|██████████| 100.0/100 [00:00<00:00, 6856.80it/s]
100%|██████████| 100.0/100 [00:00<00:00, 6795.04it/s]Failed to run subtask loUdEhp4mXVTHg0EvNzo4pom on band numa-0
Traceback (most recent call last):
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/scheduling/worker/execution.py", line 245, in internal_run_subtask
    yield asyncio.shield(run_aiotask)
  File "mars/oscar/core.pyx", line 284, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 219, in _handle_actor_result
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/api.py", line 59, in run_subtask_in_slot
    return await ref.run_subtask(subtask)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py", line 496, in send
    result = await future
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py", line 118, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 351, in __on_receive__
  File "mars/oscar/core.pyx", line 345, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 250, in _handle_actor_result
  File "mars/oscar/core.pyx", line 273, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 275, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 279, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/runner.py", line 102, in run_subtask
    result = yield self._running_processor.run(subtask)
  File "mars/oscar/core.pyx", line 284, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 219, in _handle_actor_result
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py", line 496, in send
    result = await future
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py", line 118, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 351, in __on_receive__
  File "mars/oscar/core.pyx", line 345, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 250, in _handle_actor_result
  File "mars/oscar/core.pyx", line 273, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 275, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 279, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py", line 466, in run
    result = yield self._running_aio_task
  File "mars/oscar/core.pyx", line 284, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 219, in _handle_actor_result
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py", line 361, in run
    stored_keys, store_sizes, memory_sizes = await self._store_data(chunk_graph)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py", line 259, in _store_data
    store_infos = await put_infos
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/batch.py", line 135, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/storage/api/oscar.py", line 115, in batch_put
    return await self._storage_handler_ref.put.batch(*puts)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 154, in send
    return self._process_result_message(result)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py", line 59, in _process_result_message
    raise message.error.with_traceback(message.traceback)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py", line 496, in send
    result = await future
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py", line 118, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 351, in __on_receive__
  File "mars/oscar/core.pyx", line 332, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 335, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 341, in mars.oscar.core._BaseActor.__on_receive__
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/batch.py", line 135, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/storage/handler.py", line 195, in batch_put
    object_info = await self._clients[level].put(obj)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/storage/shared_memory.py", line 159, in put
    buffers = await serializer.run()
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/aio.py", line 81, in run
    return self._get_buffers()
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/aio.py", line 39, in _get_buffers
    headers, buffers = serialize(self._obj)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py", line 339, in serialize
    result = serializer.serialize(obj, context)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py", line 75, in wrapped
    return func(self, obj, context)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py", line 152, in serialize
    return {}, pickle_buffers(obj)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py", line 89, in pickle_buffers
    buffers[0] = cloudpickle.dumps(
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/steven/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'weakref' object

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_16609/1057602519.py in <module>
----> 1 df.groupby('a')['c'].agg(lambda x: mt.sum(x))

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/dataframe/groupby/aggregation.py in agg(groupby, func, method, *args, **kwargs)
    863 
    864     if not is_funcs_aggregate(func, ndim=groupby.ndim):
--> 865         return groupby.transform(func, *args, _call_agg=True, **kwargs)
    866 
    867     use_inf_as_na = kwargs.pop('_use_inf_as_na', options.dataframe.mode.use_inf_as_na)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/dataframe/groupby/transform.py in groupby_transform(groupby, f, dtypes, dtype, name, index, output_types, *args, **kwargs)
    276     op = GroupByTransform(func=f, args=args, kwds=kwargs, output_types=output_types,
    277                           call_agg=call_agg)
--> 278     return op(groupby, dtypes=dtypes, dtype=dtype, name=name, index=index)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/core/mode.py in _inner(*args, **kwargs)
     77             def _inner(*args, **kwargs):
     78                 with self:
---> 79                     return func(*args, **kwargs)
     80         else:
     81             # async

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/dataframe/groupby/transform.py in __call__(self, groupby, dtypes, dtype, name, index)
    107             name, dtype = dtypes
    108             new_shape = (np.nan,) if self.call_agg else groupby.shape
--> 109             return self.new_series([groupby], name=name, shape=new_shape, dtype=dtype,
    110                                    index_value=index_value)
    111 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/dataframe/operands.py in new_series(self, inputs, shape, dtype, index_value, name, **kw)
     59             raise TypeError('cannot new Series with more than 1 outputs')
     60 
---> 61         return self.new_seriess(inputs, shape=shape, dtype=dtype,
     62                                 index_value=index_value, name=name, **kw)[0]
     63 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/dataframe/operands.py in new_seriess(self, inputs, shape, dtype, index_value, name, chunks, nsplits, output_limit, kws, **kw)
     51                     chunks=None, nsplits=None, output_limit=None, kws=None, **kw):
     52         setattr(self, '_output_types', [OutputType.series])
---> 53         return self.new_tileables(inputs, shape=shape, dtype=dtype, index_value=index_value,
     54                                   name=name, chunks=chunks, nsplits=nsplits,
     55                                   output_limit=output_limit, kws=kws, **kw)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/core/operand/core.py in new_tileables(self, inputs, kws, **kw)
    257         tileables = self._new_tileables(inputs, kws=kws, **kw)
    258         if is_eager_mode():
--> 259             ExecutableTuple(tileables).execute()
    260         return tileables
    261 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/core/entity/executable.py in execute(self, session, **kw)
    217 
    218         session = _get_session(self, session)
--> 219         ret = execute(*self, session=session, **kw)
    220         if kw.get('wait', True):
    221             return self

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/deploy/oscar/session.py in execute(tileable, session, wait, new_session_kwargs, show_progress, progress_update_interval, *tileables, **kwargs)
   1368             **(new_session_kwargs or dict()))
   1369     session = _ensure_sync(session)
-> 1370     return session.execute(tileable, *tileables, wait=wait,
   1371                            show_progress=show_progress,
   1372                            progress_update_interval=progress_update_interval,

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/deploy/oscar/session.py in execute(self, tileable, show_progress, *tileables, **kwargs)
   1212         fut = asyncio.run_coroutine_threadsafe(coro, self._loop)
   1213         try:
-> 1214             execution_info: ExecutionInfo = fut.result(
   1215                 timeout=self._isolated_session.timeout)
   1216         except KeyboardInterrupt:  # pragma: no cover

~/anaconda3/envs/rapids-21.08/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~/anaconda3/envs/rapids-21.08/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/deploy/oscar/session.py in _execute(session, wait, show_progress, progress_update_interval, cancelled, *tileables, **kwargs)
   1326                 while not cancelled.is_set():
   1327                     try:
-> 1328                         await asyncio.wait_for(asyncio.shield(execution_info),
   1329                                                progress_update_interval)
   1330                         # done

~/anaconda3/envs/rapids-21.08/lib/python3.8/asyncio/tasks.py in wait_for(fut, timeout, loop)
    492 
    493         if fut.done():
--> 494             return fut.result()
    495         else:
    496             fut.remove_done_callback(cb)

~/anaconda3/envs/rapids-21.08/lib/python3.8/asyncio/tasks.py in _wrap_awaitable(awaitable)
    693     that will later be wrapped in a Task by ensure_future().
    694     """
--> 695     return (yield from awaitable.__await__())
    696 
    697 _wrap_awaitable._is_coroutine = _is_coroutine

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/deploy/oscar/session.py in wait()
     76         except AttributeError:
     77             async def wait():
---> 78                 return await self._aio_task
     79 
     80             self._future_local.future = fut = \

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/deploy/oscar/session.py in _run_in_background(self, tileables, task_id, progress)
    690                         raise TimeoutError(f'Task({task_id}) running time > {self.timeout}')
    691             if task_result.error:
--> 692                 raise task_result.error.with_traceback(task_result.traceback)
    693             if cancelled:
    694                 return

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/scheduling/worker/execution.py in internal_run_subtask(self, subtask, band_name)
    243             run_aiotask = asyncio.create_task(
    244                 subtask_api.run_subtask_in_slot(band_name, slot_id, subtask))
--> 245             yield asyncio.shield(run_aiotask)
    246             if subtask_info.cancelling:
    247                 raise asyncio.CancelledError

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in _handle_actor_result()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/api.py in run_subtask_in_slot(self, band_name, slot_id, subtask)
     57         """
     58         ref = await self._get_runner_ref(band_name, slot_id)
---> 59         return await ref.run_subtask(subtask)
     60 
     61     async def cancel_subtask_in_slot(self, band_name: str, slot_id: int):

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in send(self, actor_ref, message, wait_response)
    152             if wait_response:
    153                 result = await self._wait(future, actor_ref.address, message)
--> 154                 return self._process_result_message(result)
    155             else:
    156                 return future

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in _process_result_message(message)
     57             return message.result
     58         else:
---> 59             raise message.error.with_traceback(message.traceback)
     60 
     61     async def _wait(self,

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py in send()
    494             coro = self._actors[actor_id].__on_receive__(message.content)
    495             with self._run_coro(message.message_id, coro) as future:
--> 496                 result = await future
    497             processor.result = ResultMessage(message.message_id, result,
    498                                              protocol=message.protocol)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py in __on_receive__()
    116             Message shall be (method_name,) + args + (kwargs,)
    117         """
--> 118         return await super().__on_receive__(message)
    119 
    120 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in __on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor.__on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in _handle_actor_result()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/runner.py in run_subtask()
    100         self._running_processor = self._last_processor = processor
    101         try:
--> 102             result = yield self._running_processor.run(subtask)
    103         finally:
    104             self._running_processor = None

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in _handle_actor_result()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in send()
    152             if wait_response:
    153                 result = await self._wait(future, actor_ref.address, message)
--> 154                 return self._process_result_message(result)
    155             else:
    156                 return future

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in _process_result_message()
     57             return message.result
     58         else:
---> 59             raise message.error.with_traceback(message.traceback)
     60 
     61     async def _wait(self,

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py in send()
    494             coro = self._actors[actor_id].__on_receive__(message.content)
    495             with self._run_coro(message.message_id, coro) as future:
--> 496                 result = await future
    497             processor.result = ResultMessage(message.message_id, result,
    498                                              protocol=message.protocol)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py in __on_receive__()
    116             Message shall be (method_name,) + args + (kwargs,)
    117         """
--> 118         return await super().__on_receive__(message)
    119 
    120 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in __on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor.__on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in _handle_actor_result()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py in run()
    464         self._running_aio_task = asyncio.create_task(processor.run())
    465         try:
--> 466             result = yield self._running_aio_task
    467             raise mo.Return(result)
    468         finally:

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor._run_actor_async_generator()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in _handle_actor_result()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py in run()
    359                 await self._unpin_data(input_keys)
    360             # store results data
--> 361             stored_keys, store_sizes, memory_sizes = await self._store_data(chunk_graph)
    362             # store meta
    363             await self._store_meta(chunk_graph, stored_keys, store_sizes, memory_sizes)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/subtask/worker/processor.py in _store_data()
    257             put_infos = asyncio.create_task(self._storage_api.put.batch(*puts))
    258             try:
--> 259                 store_infos = await put_infos
    260                 for store_key, store_info in zip(stored_keys, store_infos):
    261                     data_key_to_store_size[store_key] = store_info.store_size

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/batch.py in _async_batch()
    133         if self.batch_func:
    134             args_list, kwargs_list = self._gen_args_kwargs_list(delays)
--> 135             return await self.batch_func(args_list, kwargs_list)
    136         else:
    137             # this function has no batch implementation

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/storage/api/oscar.py in batch_put()
    113                     self._session_id, *args, **kwargs)
    114             )
--> 115         return await self._storage_handler_ref.put.batch(*puts)
    116 
    117     @mo.extensible

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in send()
    152             if wait_response:
    153                 result = await self._wait(future, actor_ref.address, message)
--> 154                 return self._process_result_message(result)
    155             else:
    156                 return future

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/context.py in _process_result_message()
     57             return message.result
     58         else:
---> 59             raise message.error.with_traceback(message.traceback)
     60 
     61     async def _wait(self,

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/backends/pool.py in send()
    494             coro = self._actors[actor_id].__on_receive__(message.content)
    495             with self._run_coro(message.message_id, coro) as future:
--> 496                 result = await future
    497             processor.result = ResultMessage(message.message_id, result,
    498                                              protocol=message.protocol)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/api.py in __on_receive__()
    116             Message shall be (method_name,) + args + (kwargs,)
    117         """
--> 118         return await super().__on_receive__(message)
    119 
    120 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in __on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor.__on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor.__on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/core.pyx in mars.oscar.core._BaseActor.__on_receive__()

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/oscar/batch.py in _async_batch()
    133         if self.batch_func:
    134             args_list, kwargs_list = self._gen_args_kwargs_list(delays)
--> 135             return await self.batch_func(args_list, kwargs_list)
    136         else:
    137             # this function has no batch implementation

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/services/storage/handler.py in batch_put()
    193         quota_delta = 0
    194         for size, data_key, obj in zip(sizes, data_keys, objs):
--> 195             object_info = await self._clients[level].put(obj)
    196             data_info = build_data_info(object_info, level, size, self._band_name)
    197             data_infos.append(data_info)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/storage/shared_memory.py in put()
    157 
    158         serializer = AioSerializer(obj)
--> 159         buffers = await serializer.run()
    160         buffer_size = sum(getattr(buf, 'nbytes', len(buf))
    161                           for buf in buffers)

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/aio.py in run()
     79 
     80     async def run(self):
---> 81         return self._get_buffers()
     82 
     83 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/aio.py in _get_buffers()
     37 
     38     def _get_buffers(self):
---> 39         headers, buffers = serialize(self._obj)
     40 
     41         def _is_cuda_buffer(buf):  # pragma: no cover

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py in serialize()
    337 
    338     serializer = _serial_dispatcher.get_handler(type(obj))
--> 339     result = serializer.serialize(obj, context)
    340 
    341     if not isinstance(result, types.GeneratorType):

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py in wrapped()
     73         else:
     74             context[id(obj)] = obj
---> 75             return func(self, obj, context)
     76     return wrapped
     77 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py in serialize()
    150     @buffered
    151     def serialize(self, obj, context: Dict):
--> 152         return {}, pickle_buffers(obj)
    153 
    154     def deserialize(self, header: Dict, buffers: List, context: Dict):

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/mars/serialization/core.py in pickle_buffers()
     87             buffers.append(memoryview(x))
     88 
---> 89         buffers[0] = cloudpickle.dumps(
     90             obj,
     91             buffer_callback=buffer_cb,

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py in dumps()
     71                 file, protocol=protocol, buffer_callback=buffer_callback
     72             )
---> 73             cp.dump(obj)
     74             return file.getvalue()
     75 

~/anaconda3/envs/rapids-21.08/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py in dump()
    561     def dump(self, obj):
    562         try:
--> 563             return Pickler.dump(self, obj)
    564         except RuntimeError as e:
    565             if "recursion" in e.args[0]:

TypeError: cannot pickle 'weakref' object


```

**Expected behavior**
```
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],
                   columns=['a','b','c'])
df.groupby('a')['c'].agg(lambda x: np.sum(x))

a
1    3
4    6
7    9
Name: c, dtype: int64
```

**Additional context**

**Comment by qinxuye** [comment]
Oh, for now, you cannot use Mars functions inside the user-defined functions in agg, apply and so on.

This is duplicated with #2219 .

The reason is that, for now, Mars function is sort of high-level function that apply to a huge tensor/df that has many chunks, but inside the function of apply or agg, it's sort of low-level function, that is the function is applied to a sole chunk.

We will support using mars functions inside agg or apply later, but it will take some time

**Comment by ZYLi24** [comment]
> Oh, for now, you cannot use Mars functions inside the user-defined functions in agg, apply and so on.
> 
> This is duplicated with #2219 .
> 
> The reason is that, for now, Mars function is sort of high-level function that apply to a huge tensor/df that has many chunks, but inside the function of apply or agg, it's sort of low-level function, that is the function is applied to a sole chunk.
> 
> We will support using mars functions inside agg or apply later, but it will take some time

Got it, thanks Chris
