### ISSUE TITLE
[BUG]run on ray put failed

### ISSUE THREAD

**Issue by zizouqidashen** [mars-project/mars#2638]
I try to run mars on my ray cluster , every nodes of ray cluster run 'import mars' done's well.when I run following example code from readme , got some error

code:
import ray
ray.init(address="ray://172.29.0.89:10001")
import mars
mars.new_ray_session(worker_num=5)

error:
Put failed:
.........
Can't get attribute 'RayMainPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

**Comment by hekaisheng** [comment]
Could you provide your mars version and paste the full error message?

**Comment by zizouqidashen** [comment]
when cluster all nodes has install pymars 0.8.0
```
mars.new_ray_session(worker_num=5)
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

An unexpected internal error occurred while the worker was executing a task.
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

An unexpected internal error occurred while the worker was executing a task.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff2ea5291bd9dc0d577012de214a000000 Worker ID: 4c55520305008c9303709fcc4bd652d3c6ce9e864be823d6e87cd7ec Node ID: 34598749f0b111985114f32a0edb0262256574319ebf1b92225ac895 Worker IP address: 172.24.14.249 Worker port: 10226 Worker PID: 1755519
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff4e466a12709c8a18d63316884a000000 Worker ID: df2bce56de6519d5871722cb0a7d6f217aae21563207f38cea00e6ad Node ID: 34598749f0b111985114f32a0edb0262256574319ebf1b92225ac895 Worker IP address: 172.24.14.249 Worker port: 10225 Worker PID: 1755518
(pid=None, ip=172.24.14.249) 2022-01-20 09:05:21,205	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
(pid=None, ip=172.24.14.249)     raise RuntimeError(
(pid=None, ip=172.24.14.249) RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=None, ip=172.24.14.249)     actor_class = pickle.loads(pickled_class)
(pid=None, ip=172.24.14.249) AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) During handling of the above exception, another exception occurred:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 788, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249) SystemExit
(pid=None, ip=172.24.14.249) 2022-01-20 09:05:21,206	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
(pid=None, ip=172.24.14.249)     raise RuntimeError(
(pid=None, ip=172.24.14.249) RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=None, ip=172.24.14.249)     actor_class = pickle.loads(pickled_class)
(pid=None, ip=172.24.14.249) AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) During handling of the above exception, another exception occurred:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 788, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249) SystemExit
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

An unexpected internal error occurred while the worker was executing a task.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff2ea5291bd9dc0d577012de214a000000 Worker ID: 160978644c4ecb4749cfc32fc3a53858d9e4c893f0b575e26e8027df Node ID: 34598749f0b111985114f32a0edb0262256574319ebf1b92225ac895 Worker IP address: 172.24.14.249 Worker port: 10227 Worker PID: 1755571
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

An unexpected internal error occurred while the worker was executing a task.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff4e466a12709c8a18d63316884a000000 Worker ID: 29d99b42617cb5c766124130a6f7392ca263e5ad389099701ea0a209 Node ID: 34598749f0b111985114f32a0edb0262256574319ebf1b92225ac895 Worker IP address: 172.24.14.249 Worker port: 10228 Worker PID: 1755572
(pid=None, ip=172.24.14.249) 2022-01-20 09:05:22,140	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
(pid=None, ip=172.24.14.249)     raise RuntimeError(
(pid=None, ip=172.24.14.249) RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=None, ip=172.24.14.249)     actor_class = pickle.loads(pickled_class)
(pid=None, ip=172.24.14.249) AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) During handling of the above exception, another exception occurred:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 788, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249) SystemExit
(pid=None, ip=172.24.14.249) 2022-01-20 09:05:22,164	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
(pid=None, ip=172.24.14.249)     raise RuntimeError(
(pid=None, ip=172.24.14.249) RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=None, ip=172.24.14.249)     actor_class = pickle.loads(pickled_class)
(pid=None, ip=172.24.14.249) AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) During handling of the above exception, another exception occurred:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 788, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249) SystemExit
Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
  File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
    raise RuntimeError(
RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

Traceback (most recent call last):
  File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>

An unexpected internal error occurred while the worker was executing a task.
A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff2ea5291bd9dc0d577012de214a000000 Worker ID: 3497d448d1848684c31ef617bf15ecaeee9f35df99a9fdfc81df76dc Node ID: 34598749f0b111985114f32a0edb0262256574319ebf1b92225ac895 Worker IP address: 172.24.14.249 Worker port: 10229 Worker PID: 1755621
(pid=None, ip=172.24.14.249) 2022-01-20 09:05:23,060	ERROR worker.py:431 -- SystemExit was raised from the worker
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 759, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 494, in ray._raylet.execute_task
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 512, in temporary_actor_method
(pid=None, ip=172.24.14.249)     raise RuntimeError(
(pid=None, ip=172.24.14.249) RuntimeError: The actor with name RaySubPool failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/ray/_private/function_manager.py", line 564, in _load_actor_class_from_gcs
(pid=None, ip=172.24.14.249)     actor_class = pickle.loads(pickled_class)
(pid=None, ip=172.24.14.249) AttributeError: Can't get attribute 'RaySubPool.mark_service_ready' on <module 'mars.oscar.backends.ray.pool' from '/home/panhl/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py'>
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) During handling of the above exception, another exception occurred:
(pid=None, ip=172.24.14.249) 
(pid=None, ip=172.24.14.249) Traceback (most recent call last):
(pid=None, ip=172.24.14.249)   File "python/ray/_raylet.pyx", line 788, in ray._raylet.task_execution_handler
(pid=None, ip=172.24.14.249) SystemExit
(pid=None, ip=172.24.14.249) [2022-01-20 09:05:23,062 E 1755621 1755662] core_worker.cc:298: The global worker has already been shutdown. This happens when the language frontend accesses the Ray's worker after it is shutdown. The process will exit
Traceback (most recent call last):

  File "/tmp/ipykernel_1755390/1841428437.py", line 1, in <module>
    mars.new_ray_session(worker_num=5)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 354, in new_ray_session
    client = new_cluster_in_ray(**new_cluster_kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 326, in new_cluster_in_ray
    client = fut.result()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 319, in new_cluster
    raise ex

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 311, in new_cluster
    await cluster.start()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 482, in start
    worker_pools = await asyncio.gather(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 110, in new_worker
    return await self._cluster_state_ref.new_worker(worker_address)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/oscar/backends/context.py", line 177, in send
    return self._process_result_message(result)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/oscar/backends/context.py", line 69, in _process_result_message
    raise message.error.with_traceback(message.traceback)

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/pool.py", line 520, in send

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/pool.py", line 319, in _run_coro

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/api.py", line 115, in __on_receive__

  File "mars/oscar/core.pyx", line 366, in __on_receive__
    raise ex

  File "mars/oscar/core.pyx", line 338, in mars.oscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',

  File "mars/oscar/core.pyx", line 341, in mars.oscar.core._BaseActor.__on_receive__
    async with self._lock:

  File "mars/oscar/core.pyx", line 344, in mars.oscar.core._BaseActor.__on_receive__
    result = await result

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 200, in new_worker

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/deploy/oscar/pool.py", line 81, in create_worker_actor_pool

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/api.py", line 58, in create_actor_pool

  File "/home/sys-admin/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/backend.py", line 62, in create_actor_pool

RayTaskError: ray::RayMainPool.start() (pid=2433967, ip=172.29.0.89, repr=<mars.oscar.backends.ray.pool.RayMainPool object at 0x7fe3715c9100>)
  File "/root/miniconda3/envs/raycluster/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/root/miniconda3/envs/raycluster/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py", line 260, in start
    self._actor_pool = await create_actor_pool(
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/pool.py", line 1231, in create_actor_pool
    pool: MainActorPoolType = await pool_cls.create(
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/pool.py", line 987, in create
    processes = await cls.wait_sub_pools_ready(tasks)
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py", line 126, in wait_sub_pools_ready
    return [await t for t in create_pool_tasks]
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py", line 126, in <listcomp>
    return [await t for t in create_pool_tasks]
  File "/root/miniconda3/envs/raycluster/lib/python3.9/site-packages/mars/oscar/backends/ray/pool.py", line 121, in start_sub_pool
    await actor_handle.start.remote()
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

uninstall pymars from every nodes
```
mars.new_ray_session(worker_num=5)
Put failed:
2022-01-20 09:00:35,124	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,124	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,125	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,125	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,126	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,126	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,127	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,127	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
2022-01-20 09:00:35,127	INFO threading.py:234 -- Exception from actor creation is ignored in destructor. To receive this exception in application code, call a method on the actor reference before its destructor is run.
Traceback (most recent call last):

  File "/tmp/ipykernel_1754372/1841428437.py", line 1, in <module>
    mars.new_ray_session(worker_num=5)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 354, in new_ray_session
    client = new_cluster_in_ray(**new_cluster_kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 326, in new_cluster_in_ray
    client = fut.result()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 319, in new_cluster
    raise ex

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 311, in new_cluster
    await cluster.start()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/ray.py", line 461, in start
    self._supervisor_pool = await create_supervisor_actor_pool(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/deploy/oscar/pool.py", line 36, in create_supervisor_actor_pool
    return await mo.create_actor_pool(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/oscar/api.py", line 58, in create_actor_pool
    return await get_backend(scheme).create_actor_pool(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/mars/oscar/backends/ray/backend.py", line 51, in create_actor_pool
    ray.remote(RayMainPool)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/actor.py", line 505, in remote
    return actor_cls._remote(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 371, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/actor.py", line 618, in _remote
    return client_mode_convert_actor(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 193, in client_mode_convert_actor
    return client_actor._remote(in_args, in_kwargs, **kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/common.py", line 225, in _remote
    return self.options(**option_args).remote(*args, **kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/common.py", line 401, in remote
    futures = ray.call_remote(self, *args, **kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/api.py", line 106, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/worker.py", line 449, in call_remote
    task = instance._prepare_client_task()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/common.py", line 386, in _prepare_client_task
    task = self._remote_stub._prepare_client_task()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/common.py", line 236, in _prepare_client_task
    self._ensure_ref()

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/common.py", line 207, in _ensure_ref
    self._ref = ray.worker._put_pickled(

  File "/home/panhl/miniconda3/envs/money/lib/python3.9/site-packages/ray/util/client/worker.py", line 407, in _put_pickled
    raise cloudpickle.loads(resp.error)

ModuleNotFoundError: No module named 'mars'
```

**Comment by zizouqidashen** [comment]
I have seen not all mars.version are same in every node , it work good after fit

**Comment by qinxuye** [comment]
Thank you, feel free to reach out to us if any issue occurs.
