### ISSUE TITLE
[BUG] Dev installation failing on Python 3.8

### ISSUE THREAD

**Issue by sakshamkumar-byt** [mars-project/mars#2673]
**Describe the bug**
While trying to dev install mars project on Python 3.8 on OSX using the following steps mentioned on [Setting Up a Development Environment](https://docs.pymars.org/en/latest/development/contributing.html#setting-up-a-development-environment)

```
pip install --upgrade setuptools pip
pip install cython
git clone https://github.com/mars-project/mars.git
cd mars
pip install -e ".[dev]"
```

The user is first prompted the following

```
pip install -e ".[dev]"
Obtaining file:///Users/dev/mars-exp/mars
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/dev/mars-exp/mars/setup.py", line 27, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

On installing numpy with pip and re-runing the user gets a long cython related error. A small snippet of the same is:

```
     ------------------------------------------------------------
      
      mars/learn/utils/_cython_blas.pyx:203:33: Converting to Python object not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if floating is float:
                  sgemm(&ta_, &tb_, &m, &n, &k, &alpha, A,
                        &lda, B, &ldb, &beta, C, &ldc)
              else:
                  dgemm(&ta_, &tb_, &m, &n, &k, &alpha, A,
                        &lda, B, &ldb, &beta, C, &ldc)
                                             ^
      ------------------------------------------------------------
      
      mars/learn/utils/_cython_blas.pyx:203:40: Converting to Python object not allowed without gil
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              if floating is float:
                  sgemm(&ta_, &tb_, &m, &n, &k, &alpha, A,
                        &lda, B, &ldb, &beta, C, &ldc)
              else:
                  dgemm(&ta_, &tb_, &m, &n, &k, &alpha, A,
                        &lda, B, &ldb, &beta, C, &ldc)
                                                ^
      ------------------------------------------------------------
      
      mars/learn/utils/_cython_blas.pyx:203:43: Converting to Python object not allowed without gil
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/dev/mars/setup.py", line 121, in <module>
          extensions = cythonize(cy_extensions, **cythonize_kw) + [
        File "/Users/dev/venv_ray_exp/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1127, in cythonize
          cythonize_one(*args)
        File "/Users/dev/venv_ray_exp/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1250, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: mars/learn/utils/_cython_blas.pyx
      Compiling mars/_utils.pyx because it changed.
      Compiling mars/oscar/context.pyx because it changed.
      Compiling mars/oscar/core.pyx because it changed.
      Compiling mars/oscar/utils.pyx because it changed.
      Compiling mars/learn/cluster/_k_means_elkan.pyx because it changed.
      Compiling mars/learn/cluster/_k_means_lloyd.pyx because it changed.
      Compiling mars/learn/cluster/_k_means_fast.pyx because it changed.
      Compiling mars/learn/utils/_cython_blas.pyx because it changed.
      Compiling mars/core/graph/core.pyx because it changed.
      [1/9] Cythonizing mars/_utils.pyx
      [2/9] Cythonizing mars/core/graph/core.pyx
      [3/9] Cythonizing mars/learn/cluster/_k_means_elkan.pyx
      [4/9] Cythonizing mars/learn/cluster/_k_means_fast.pyx
      [5/9] Cythonizing mars/learn/cluster/_k_means_lloyd.pyx
      [6/9] Cythonizing mars/learn/utils/_cython_blas.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version - Python 3.8.9

2. The version of Mars you use - Building from master
3. Versions of crucial packages, such as numpy, scipy and pandas
```
pip freeze
Cython==0.29.27
numpy==1.22.1
```
4. Full stack of the error. - The full stack is a little too long, will try to post in comments

**Comment by sakshamkumar-byt** [comment]
Full trace
[stack.txt](https://github.com/mars-project/mars/files/7980353/stack.txt)

**Comment by sakshamkumar-byt** [comment]
Hi @wjsi 
Thanks for replying. But I see the same error with numpy 1.20.3

```
pip freeze
Cython==0.29.27
numpy==1.20.3
```

Is there a particular Cython version that you are looking for?

**Comment by sakshamkumar-byt** [comment]
@wjsi 
Seems like installing scipy manually did the trick

`
scipy==1.7.3
`

Referred : https://github.com/google/jax/issues/375

**Comment by wjsi** [comment]
> @wjsi Seems like installing scipy manually did the trick
> 
> `scipy==1.7.3`
> 
> Referred : [google/jax#375](https://github.com/google/jax/issues/375)

Thanks for the report. We are adding a `pyproject.toml` to specify build requirements. This issue will be resolved then.
