### ISSUE TITLE
[BUG]mars.new_ray_session  error

### ISSUE THREAD

**Issue by jyizheng** [mars-project/mars#2762]
**Describe the bug**

Create a mars session on ray cluster has an error.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version

3.7.7

3. The version of Mars you use

0.9.0b1

4. Versions of crucial packages, such as numpy, scipy and pandas

  numpy==1.21.5 pandas==1.3.5 pymars==0.9.0b1 xgboost "xgboost_ray" lightgbm

5. Full stack of the error.

(base) root@cd15e694a26a:~# python
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ray
>>> import mars
>>> ray.init(address='ray://10.227.144.220:30772')
ClientContext(dashboard_url='127.0.0.1:8265', python_version='3.7.7', ray_version='1.9.2', ray_commit='ef593fe5d3c864836b80ae77be32635cef42b537', protocol_version='2021-09-22', _num_clients=1, _context_to_restore=<ray.util.client._ClientContext object at 0x7fb75b902190>)
>>> import mars.tensor as mt
>>> import mars.dataframe as md
>>> session = mars.new_ray_session(worker_num=2, worker_mem=2 * 1024 ** 3)
(RayMainPool pid=671, ip=172.20.150.197) 2022-02-27 23:46:24,651	ERROR serialization.py:283 -- 'pickle'
(RayMainPool pid=671, ip=172.20.150.197) Traceback (most recent call last):
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 281, in deserialize_objects
(RayMainPool pid=671, ip=172.20.150.197)     obj = self._deserialize_object(data, metadata, object_ref)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 78, in _deserialize_object
(RayMainPool pid=671, ip=172.20.150.197)     message = deserialize(*value.message)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 423, in deserialize
(RayMainPool pid=671, ip=172.20.150.197)     gen_deserialized = _deserialize(*gen_to_deserial)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 397, in _deserialize
(RayMainPool pid=671, ip=172.20.150.197)     serializer = _deserializers[serializer_name]
(RayMainPool pid=671, ip=172.20.150.197) KeyError: 'pickle'
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 320, in new_cluster
    await cluster.start()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 481, in start
    NodeRole.WORKER, self.supervisor_address, self.supervisor_address
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 95, in create
    address=lookup_address,
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/api.py", line 27, in create_actor
    return await ctx.create_actor(actor_cls, *args, uid=uid, address=address, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 105, in create_actor
    result = await self._wait(future, address, create_actor_message)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 83, in _wait
    return await future
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 74, in _wait
    await asyncio.shield(future)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/core.py", line 49, in _listen
    message: _MessageBase = await client.recv()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/communication/base.py", line 262, in recv
    return await self.channel.recv()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 196, in recv
    result = await object_ref
ray.exceptions.RayTaskError: ray::RayMainPool.__on_ray_recv__() (pid=671, ip=172.20.150.197, repr=<mars.oscar.backends.ray.pool.RayMainPool object at 0x7f1565adcdc0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: 'pickle'
traceback: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 281, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 78, in _deserialize_object
    message = deserialize(*value.message)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 423, in deserialize
    gen_deserialized = _deserialize(*gen_to_deserial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 397, in _deserialize
    serializer = _deserializers[serializer_name]
KeyError: 'pickle'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 363, in new_ray_session
    client = new_cluster_in_ray(**new_cluster_kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 335, in new_cluster_in_ray
    client = fut.result()
  File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ray/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 327, in new_cluster
    raise stop_ex from ex
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 325, in new_cluster
    await cluster.stop()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/ray.py", line 519, in stop
    await stop_supervisor(self.supervisor_address, self._config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/deploy/oscar/service.py", line 66, in stop_supervisor
    await stop_services(NodeRole.SUPERVISOR, address=address, config=config)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/services/core.py", line 185, in stop_services
    await asyncio.gather(*[inst.stop() for inst in instances])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/services/task/supervisor/service.py", line 52, in stop
    uid=TaskConfigurationActor.default_uid(), address=self._address
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/api.py", line 37, in destroy_actor
    return await ctx.destroy_actor(actor_ref)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 121, in destroy_actor
    result = await self._wait(future, actor_ref.address, message)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 83, in _wait
    return await future
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 74, in _wait
    await asyncio.shield(future)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/core.py", line 49, in _listen
    message: _MessageBase = await client.recv()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/communication/base.py", line 262, in recv
    return await self.channel.recv()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 196, in recv
    result = await object_ref
ray.exceptions.RayTaskError: ray::RayMainPool.__on_ray_recv__() (pid=671, ip=172.20.150.197, repr=<mars.oscar.backends.ray.pool.RayMainPool object at 0x7f1565adcdc0>)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: 'pickle'
traceback: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 281, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 78, in _deserialize_object
    message = deserialize(*value.message)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 423, in deserialize
    gen_deserialized = _deserialize(*gen_to_deserial)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 397, in _deserialize
    serializer = _deserializers[serializer_name]
KeyError: 'pickle'
>>> (RayMainPool pid=671, ip=172.20.150.197) 2022-02-27 23:46:24,700	ERROR serialization.py:283 -- 'pickle'
(RayMainPool pid=671, ip=172.20.150.197) Traceback (most recent call last):
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 281, in deserialize_objects
(RayMainPool pid=671, ip=172.20.150.197)     obj = self._deserialize_object(data, metadata, object_ref)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/oscar/backends/ray/communication.py", line 78, in _deserialize_object
(RayMainPool pid=671, ip=172.20.150.197)     message = deserialize(*value.message)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 423, in deserialize
(RayMainPool pid=671, ip=172.20.150.197)     gen_deserialized = _deserialize(*gen_to_deserial)
(RayMainPool pid=671, ip=172.20.150.197)   File "/home/ray/anaconda3/lib/python3.7/site-packages/mars/serialization/core.py", line 397, in _deserialize
(RayMainPool pid=671, ip=172.20.150.197)     serializer = _deserializers[serializer_name]
(RayMainPool pid=671, ip=172.20.150.197) KeyError: 'pickle'
>>> exit()

7. Minimized code to reproduce the error.

```python
import ray
import mars
ray.init(address='ray://10.227.144.220:30772') # ray cluster wit h3 node  with ray version 1.9.2

import mars.tensor as mt
import mars.dataframe as md
session = mars.new_ray_session(worker_num=2, worker_mem=2 * 1024 ** 3)
```

**Expected behavior**

KeyError: 'pickle'

**Additional context**

Ray cluster docker is built with the following docker file: 

ARG BASE_IMAGE=rayproject/ray:1.9.2
FROM ${BASE_IMAGE}

```YAML
# Setup commands[Optional]
RUN sudo apt-get update \
    && sudo apt-get upgrade -y \
    && sudo apt-get install -y emacs vim\
    && sudo apt-get clean \
    && sudo rm -rf /var/lib/apt/lists/*

# ML packages[Optional]
RUN pip3 install  numpy==1.21.5 pandas==1.3.5 pymars==0.9.0b1 xgboost "xgboost_ray" lightgbm
```

**Comment by qinxuye** [comment]
@chaokunyang could you please take a look?

**Comment by chaokunyang** [comment]
Hi @jyizheng，your code works on my mac machine without using docker and ray client. Have you tried the code without ray client? Seems it's related with ray client. Have you tried out without ray client?

**Comment by jyizheng** [comment]
@chaokunyang , thanks for the reply. We really want to run mars on a ray cluster. 
I have tried the steps here: https://github.com/mars-project/mars#mars-on-ray

But I cannot run these lines of code successfully.  Can you ?
