### ISSUE TITLE
[BUG]raise exception after xgb fit

### ISSUE THREAD

**Issue by wuyeguo** [mars-project/mars#2816]
**Describe the bug**
raise exception after xgb fit
my code like this
```
[ray@ml-test ~]$ cat test_mars_xgb.py
import ray
ray.init(address="ray://172.16.210.22:10001")

import mars
import mars.tensor as mt
import mars.dataframe as md
session = mars.new_ray_session(worker_num=2, worker_mem=2 * 1024 ** 3)

from sklearn.datasets import load_boston
boston = load_boston()

data = md.DataFrame(boston.data, columns=boston.feature_names)

print("data.head().execute()")
print(data.head().execute())

print("data.describe().execute()")
print(data.describe().execute())

from mars.learn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, boston.target, train_size=0.7, random_state=0)

print("after split X_train: %s" % X_train)

from mars.learn.contrib import xgboost as xgb

train_dmatrix = xgb.MarsDMatrix(data=X_train, label=y_train)
test_dmatrix = xgb.MarsDMatrix(data=X_test, label=y_test)

print("train_dmatrix: %s" % train_dmatrix)

#params = {'objective': 'reg:squarederror','colsample_bytree': 0.3,'learning_rate': 0.1, 'max_depth': 5, 'alpha': 10, 'n_estimators': 10}

#booster = xgb.train(dtrain=train_dmatrix, params=params)

#xg_reg = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1, max_depth=5, alpha=10, n_estimators=10)
xg_reg = xgb.XGBRegressor()

print("xg_reg.fit %s" % xg_reg)

model = xg_reg.fit(X_train, y_train, session=session)

#xgb.predict(booster, X_test)

print("results.predict")

test_r = model.predict(X_test)

print("output:test_r:%s" % type(test_r))
print(test_r)


```

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version：3.7.5
2. The version of Mars you use：commit：4474103aa61ffbb08d62481388a3e1c7f9dba98d
3. Versions of crucial packages, such as numpy, scipy and pandas
   1. Ray：1.9.2
   2. Numpy：1.21.5
   3. Pandas：1.3.5
   4. Scipy：1.7.3
   5. xgboost：1.5.2
4. Full stack of the error.
```
277   0.06127  40.0   6.41   1.0  0.447  6.826  27.6  4.8628   4.0  254.0     17.6  393.45   4.16

[354 rows x 13 columns]
train_dmatrix: DataFrame(op=ToDMatrix)
xg_reg.fit XGBRegressor()
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 80.0/100 [00:01<00:00, 79.97it/s](RayMainPool pid=None) Subtask rQAkuIap1FhSKYLNSuZwetTI errored
(RayMainPool pid=None) Traceback (most recent call last):
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 332, in internal_run_subtask
(RayMainPool pid=None)     subtask, band_name, subtask_api, batch_quota_req
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 420, in _retry_run_subtask
(RayMainPool pid=None)     return await _retry_run(subtask, subtask_info, _run_subtask_once)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 91, in _retry_run
(RayMainPool pid=None)     raise ex
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 67, in _retry_run
(RayMainPool pid=None)     return await target_async_func(*args)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 408, in _run_subtask_once
(RayMainPool pid=None)     raise ex
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 373, in _run_subtask_once
(RayMainPool pid=None)     return await asyncio.shield(aiotask)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/api.py", line 69, in run_subtask_in_slot
(RayMainPool pid=None)     subtask
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
(RayMainPool pid=None)     return self._process_result_message(result)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
(RayMainPool pid=None)     raise message.as_instanceof_cause()
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
(RayMainPool pid=None)     result = await self._run_coro(message.message_id, coro)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
(RayMainPool pid=None)     return await coro
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
(RayMainPool pid=None)     return await super().__on_receive__(message)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 373, in __on_receive__
(RayMainPool pid=None)     raise ex
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
(RayMainPool pid=None)     return await self._handle_actor_result(result)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 252, in _handle_actor_result
(RayMainPool pid=None)     task_result = await coros[0]
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     with debug_async_timeout('actor_lock_timeout',
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     async with self._lock:
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     res = await gen.athrow(*res)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/runner.py", line 118, in run_subtask
(RayMainPool pid=None)     result = yield self._running_processor.run(subtask)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     res = await self._handle_actor_result(res)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 226, in _handle_actor_result
(RayMainPool pid=None)     result = await result
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
(RayMainPool pid=None)     return self._process_result_message(result)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
(RayMainPool pid=None)     raise message.as_instanceof_cause()
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
(RayMainPool pid=None)     result = await self._run_coro(message.message_id, coro)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
(RayMainPool pid=None)     return await coro
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
(RayMainPool pid=None)     return await super().__on_receive__(message)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 373, in __on_receive__
(RayMainPool pid=None)     raise ex
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
(RayMainPool pid=None)     return await self._handle_actor_result(result)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 252, in _handle_actor_result
(RayMainPool pid=None)     task_result = await coros[0]
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     with debug_async_timeout('actor_lock_timeout',
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     async with self._lock:
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     res = await gen.athrow(*res)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 596, in run
(RayMainPool pid=None)     result = yield self._running_aio_task
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None)     res = await self._handle_actor_result(res)
(RayMainPool pid=None)   File "mars/oscar/core.pyx", line 226, in _handle_actor_result
(RayMainPool pid=None)     result = await result
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 457, in run
(RayMainPool pid=None)     await self._execute_graph(chunk_graph)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 209, in _execute_graph
(RayMainPool pid=None)     await to_wait
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/lib/aio/_threads.py", line 36, in to_thread
(RayMainPool pid=None)     return await loop.run_in_executor(None, func_call)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
(RayMainPool pid=None)     result = self.fn(*self.args, **self.kwargs)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/core/mode.py", line 77, in _inner
(RayMainPool pid=None)     return func(*args, **kwargs)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 177, in _execute_operand
(RayMainPool pid=None)     return execute(ctx, op)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/core/operand/core.py", line 489, in execute
(RayMainPool pid=None)     result = executor(results, op)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/start_tracker.py", line 55, in execute
(RayMainPool pid=None)     hostIP=ctx.current_address.split(":", 1)[0], nslave=op.n_workers
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 159, in __init__
(RayMainPool pid=None)     sock = socket.socket(get_family(hostIP), socket.SOCK_STREAM)
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 70, in get_family
(RayMainPool pid=None)     return socket.getaddrinfo(addr, None)[0][0]
(RayMainPool pid=None)   File "/usr/local/python3/lib/python3.7/socket.py", line 748, in getaddrinfo
(RayMainPool pid=None)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(RayMainPool pid=None) mars.utils.gaierror: [address=ray://ray-cluster-1647246620/0/3, pid=16013] [Errno -2] Name or service not known
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:01<00:00, 62.42it/s]
Traceback (most recent call last):
  File "test_mars_xgb.py", line 42, in <module>
    model = xg_reg.fit(X_train, y_train, session=session)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/regressor.py", line 68, in fit
    run_kwargs=run_kwargs,
  File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/train.py", line 255, in train
    ret = t.execute(session=session, **run_kwargs).fetch(session=session)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/core/entity/executable.py", line 98, in execute
    return execute(self, session=session, **kw)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/deploy/oscar/session.py", line 1785, in execute
    **kwargs,
  File "/usr/local/python3/lib/python3.7/site-packages/mars/deploy/oscar/session.py", line 1578, in execute
    timeout=self._isolated_session.timeout
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/local/python3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/python3/lib/python3.7/site-packages/mars/deploy/oscar/session.py", line 1759, in _execute
    await execution_info
  File "/usr/local/python3/lib/python3.7/site-packages/mars/deploy/oscar/session.py", line 102, in wait
    return await self._aio_task
  File "/usr/local/python3/lib/python3.7/site-packages/mars/deploy/oscar/session.py", line 907, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 332, in internal_run_subtask
    subtask, band_name, subtask_api, batch_quota_req
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 420, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 91, in _retry_run
    raise ex
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 67, in _retry_run
    return await target_async_func(*args)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 408, in _run_subtask_once
    raise ex
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 373, in _run_subtask_once
    return await asyncio.shield(aiotask)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/api.py", line 69, in run_subtask_in_slot
    subtask
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
    return self._process_result_message(result)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
    return await coro
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 373, in __on_receive__
  File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 252, in _handle_actor_result
  File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/runner.py", line 118, in run_subtask
    result = yield self._running_processor.run(subtask)
  File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 226, in _handle_actor_result
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
    return self._process_result_message(result)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
    return await coro
  File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 373, in __on_receive__
  File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
  File "mars/oscar/core.pyx", line 252, in _handle_actor_result
  File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 596, in run
    result = yield self._running_aio_task
  File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
  File "mars/oscar/core.pyx", line 226, in _handle_actor_result
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 457, in run
    await self._execute_graph(chunk_graph)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 209, in _execute_graph
    await to_wait
  File "/usr/local/python3/lib/python3.7/site-packages/mars/lib/aio/_threads.py", line 36, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/local/python3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/core/mode.py", line 77, in _inner
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 177, in _execute_operand
    return execute(ctx, op)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/core/operand/core.py", line 489, in execute
    result = executor(results, op)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/start_tracker.py", line 55, in execute
    hostIP=ctx.current_address.split(":", 1)[0], nslave=op.n_workers
  File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 159, in __init__
    sock = socket.socket(get_family(hostIP), socket.SOCK_STREAM)
  File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 70, in get_family
    return socket.getaddrinfo(addr, None)[0][0]
  File "/usr/local/python3/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
mars.utils.gaierror: [address=ray://ray-cluster-1647246620/0/3, pid=16013] [Errno -2] Name or service not known
(RayMainPool pid=None, ip=172.16.210.21) Failed to run subtask rQAkuIap1FhSKYLNSuZwetTI on band numa-0
(RayMainPool pid=None, ip=172.16.210.21) Traceback (most recent call last):
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 332, in internal_run_subtask
(RayMainPool pid=None, ip=172.16.210.21)     subtask, band_name, subtask_api, batch_quota_req
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 420, in _retry_run_subtask
(RayMainPool pid=None, ip=172.16.210.21)     return await _retry_run(subtask, subtask_info, _run_subtask_once)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 91, in _retry_run
(RayMainPool pid=None, ip=172.16.210.21)     raise ex
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 67, in _retry_run
(RayMainPool pid=None, ip=172.16.210.21)     return await target_async_func(*args)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 408, in _run_subtask_once
(RayMainPool pid=None, ip=172.16.210.21)     raise ex
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/scheduling/worker/execution.py", line 373, in _run_subtask_once
(RayMainPool pid=None, ip=172.16.210.21)     return await asyncio.shield(aiotask)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/api.py", line 69, in run_subtask_in_slot
(RayMainPool pid=None, ip=172.16.210.21)     subtask
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
(RayMainPool pid=None, ip=172.16.210.21)     return self._process_result_message(result)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
(RayMainPool pid=None, ip=172.16.210.21)     raise message.as_instanceof_cause()
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
(RayMainPool pid=None, ip=172.16.210.21)     result = await self._run_coro(message.message_id, coro)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
(RayMainPool pid=None, ip=172.16.210.21)     return await coro
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     return await super().__on_receive__(message)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 373, in __on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     raise ex
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     return await self._handle_actor_result(result)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 252, in _handle_actor_result
(RayMainPool pid=None, ip=172.16.210.21)     task_result = await coros[0]
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     with debug_async_timeout('actor_lock_timeout',
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     async with self._lock:
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     res = await gen.athrow(*res)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/runner.py", line 118, in run_subtask
(RayMainPool pid=None, ip=172.16.210.21)     result = yield self._running_processor.run(subtask)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     res = await self._handle_actor_result(res)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 226, in _handle_actor_result
(RayMainPool pid=None, ip=172.16.210.21)     result = await result
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 186, in send
(RayMainPool pid=None, ip=172.16.210.21)     return self._process_result_message(result)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/context.py", line 70, in _process_result_message
(RayMainPool pid=None, ip=172.16.210.21)     raise message.as_instanceof_cause()
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 535, in send
(RayMainPool pid=None, ip=172.16.210.21)     result = await self._run_coro(message.message_id, coro)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/backends/pool.py", line 326, in _run_coro
(RayMainPool pid=None, ip=172.16.210.21)     return await coro
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/oscar/api.py", line 115, in __on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     return await super().__on_receive__(message)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 373, in __on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     raise ex
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 367, in mars.oscar.core._BaseActor.__on_receive__
(RayMainPool pid=None, ip=172.16.210.21)     return await self._handle_actor_result(result)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 252, in _handle_actor_result
(RayMainPool pid=None, ip=172.16.210.21)     task_result = await coros[0]
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 295, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     with debug_async_timeout('actor_lock_timeout',
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 297, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     async with self._lock:
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 301, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     res = await gen.athrow(*res)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 596, in run
(RayMainPool pid=None, ip=172.16.210.21)     result = yield self._running_aio_task
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 306, in mars.oscar.core._BaseActor._run_actor_async_generator
(RayMainPool pid=None, ip=172.16.210.21)     res = await self._handle_actor_result(res)
(RayMainPool pid=None, ip=172.16.210.21)   File "mars/oscar/core.pyx", line 226, in _handle_actor_result
(RayMainPool pid=None, ip=172.16.210.21)     result = await result
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 457, in run
(RayMainPool pid=None, ip=172.16.210.21)     await self._execute_graph(chunk_graph)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 209, in _execute_graph
(RayMainPool pid=None, ip=172.16.210.21)     await to_wait
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/lib/aio/_threads.py", line 36, in to_thread
(RayMainPool pid=None, ip=172.16.210.21)     return await loop.run_in_executor(None, func_call)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
(RayMainPool pid=None, ip=172.16.210.21)     result = self.fn(*self.args, **self.kwargs)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/core/mode.py", line 77, in _inner
(RayMainPool pid=None, ip=172.16.210.21)     return func(*args, **kwargs)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/services/subtask/worker/processor.py", line 177, in _execute_operand
(RayMainPool pid=None, ip=172.16.210.21)     return execute(ctx, op)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/core/operand/core.py", line 489, in execute
(RayMainPool pid=None, ip=172.16.210.21)     result = executor(results, op)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/start_tracker.py", line 55, in execute
(RayMainPool pid=None, ip=172.16.210.21)     hostIP=ctx.current_address.split(":", 1)[0], nslave=op.n_workers
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 159, in __init__
(RayMainPool pid=None, ip=172.16.210.21)     sock = socket.socket(get_family(hostIP), socket.SOCK_STREAM)
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/site-packages/mars/learn/contrib/xgboost/tracker.py", line 70, in get_family
(RayMainPool pid=None, ip=172.16.210.21)     return socket.getaddrinfo(addr, None)[0][0]
(RayMainPool pid=None, ip=172.16.210.21)   File "/usr/local/python3/lib/python3.7/socket.py", line 748, in getaddrinfo
(RayMainPool pid=None, ip=172.16.210.21)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(RayMainPool pid=None, ip=172.16.210.21) mars.utils.gaierror: [address=ray://ray-cluster-1647246620/0/3, pid=16013] [Errno -2] Name or service not known
Exception ignored in: <function _TileableSession.__init__.<locals>.cb at 0x7f839f39ba70>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/mars/core/entity/executable.py", line 52, in cb
  File "/usr/local/python3/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
RuntimeError: cannot schedule new futures after shutdown
Exception ignored in: <function _TileableSession.__init__.<locals>.cb at 0x7f839f395710>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/mars/core/entity/executable.py", line 52, in cb
  File "/usr/local/python3/lib/python3.7/concurrent/futures/thread.py", line 163, in submit
RuntimeError: cannot schedule new futures after shutdown

```

6. Minimized code to reproduce the error.

**Expected behavior**

**Additional context**

**Comment by qinxuye** [comment]
Thanks for your report, will fix it ASAP.

**Comment by hekaisheng** [comment]
It's due to the wrong address from context when xgboost start its tracker, we need to do something to get host IP when execute in Ray cluster, here is the related code:
https://github.com/mars-project/mars/blob/c91d5a70e6d4805ff8b037e18ff238fe58ea391b/mars/learn/contrib/xgboost/start_tracker.py#L54-L56

Any idea about getting host IP for Ray cluster? @fyrestone @chaokunyang

**Comment by chaokunyang** [comment]
> It's due to the wrong address from context when xgboost starts its tracker, we need to do something to get host IP when execute in Ray cluster, here is the related code:
> 
> https://github.com/mars-project/mars/blob/c91d5a70e6d4805ff8b037e18ff238fe58ea391b/mars/learn/contrib/xgboost/start_tracker.py#L54-L56
> 
> Any idea about getting host IP for Ray cluster? @fyrestone @chaokunyang

Ray has an util function `ray.util.get_node_ip_address()` which can be used to get node ip address.
