### ISSUE TITLE
[BUG] Deref stage may raises AssertionError: chunk key xxx will have negative ref count

### ISSUE THREAD

**Issue by fyrestone** [mars-project/mars#2896]
**Describe the bug**

Try to run the `pytest -s -v --log-cli-level=debug mars/dataframe/groupby/tests/test_groupby_execution.py::test_groupby_sample` in the latest master.

The test case will be ***PASSED***, but there is an unretrieved task exception:

```python
ERROR    asyncio:isolation.py:36 Task exception was never retrieved
future: <Task finished coro=<<coroutine without __name__>()> exception=AssertionError('chunk key fba521b5c44e2f43199042f58b5fa971_0 will have negative ref count')>
Traceback (most recent call last):
  File "mars/oscar/core.pyx", line 251, in __pyx_actor_method_wrapper
    return await result_handler(result)
  File "mars/oscar/core.pyx", line 385, in _handle_actor_result
    task_result = await coros[0]
  File "mars/oscar/core.pyx", line 428, in mars.oscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "mars/oscar/core.pyx", line 429, in mars.oscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "mars/oscar/core.pyx", line 434, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await gen.athrow(*res)
  File "/home/admin/mars-ant/mars/services/task/supervisor/processor.py", line 655, in start
    yield processor.decref_stage.batch(*decrefs)
  File "mars/oscar/core.pyx", line 439, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await self._handle_actor_result(res)
  File "mars/oscar/core.pyx", line 359, in _handle_actor_result
    result = await result
  File "/home/admin/mars-ant/mars/oscar/batch.py", line 148, in _async_batch
    return [await self._async_call(*d.args, **d.kwargs)]
  File "/home/admin/mars-ant/mars/oscar/batch.py", line 95, in _async_call
    return await self.func(*args, **kwargs)
  File "/home/admin/mars-ant/mars/services/task/supervisor/processor.py", line 67, in inner
    return await func(processor, *args, **kwargs)
  File "/home/admin/mars-ant/mars/services/task/supervisor/processor.py", line 288, in decref_stage
    await self._lifecycle_api.decref_chunks(decref_chunk_keys)
  File "/home/admin/mars-ant/mars/services/lifecycle/api/oscar.py", line 134, in decref_chunks
    return await self._lifecycle_tracker_ref.decref_chunks(chunk_keys)
  File "mars/oscar/core.pyx", line 251, in __pyx_actor_method_wrapper
    return await result_handler(result)
  File "mars/oscar/core.pyx", line 385, in _handle_actor_result
    task_result = await coros[0]
  File "mars/oscar/core.pyx", line 428, in mars.oscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "mars/oscar/core.pyx", line 429, in mars.oscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "mars/oscar/core.pyx", line 432, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await gen.asend(res)
  File "/home/admin/mars-ant/mars/services/lifecycle/supervisor/tracker.py", line 94, in decref_chunks
    to_remove_chunk_keys = self._get_remove_chunk_keys(chunk_keys)
  File "/home/admin/mars-ant/mars/services/lifecycle/supervisor/tracker.py", line 82, in _get_remove_chunk_keys
    assert ref_count >= 0, f"chunk key {chunk_key} will have negative ref count"
AssertionError: chunk key fba521b5c44e2f43199042f58b5fa971_0 will have negative ref count
```

The exception may be caused by the operand execution error:

```python
ERROR    mars.services.task.supervisor.stage:stage.py:172 Subtask gTsCHkuFyK77u7ahMDUJzxD0 errored
Traceback (most recent call last):
  File "/home/admin/mars-ant/mars/services/scheduling/worker/execution.py", line 356, in internal_run_subtask
    subtask, band_name, subtask_api, batch_quota_req
  File "/home/admin/mars-ant/mars/services/scheduling/worker/execution.py", line 456, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "/home/admin/mars-ant/mars/services/scheduling/worker/execution.py", line 107, in _retry_run
    raise ex
  File "/home/admin/mars-ant/mars/services/scheduling/worker/execution.py", line 67, in _retry_run
    return await target_async_func(*args)
  File "/home/admin/mars-ant/mars/services/scheduling/worker/execution.py", line 398, in _run_subtask_once
    return await asyncio.shield(aiotask)
  File "/home/admin/mars-ant/mars/services/subtask/api.py", line 69, in run_subtask_in_slot
    subtask
  File "/home/admin/mars-ant/mars/oscar/backends/context.py", line 190, in send
    return self._process_result_message(result)
  File "/home/admin/mars-ant/mars/oscar/backends/context.py", line 70, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/admin/mars-ant/mars/oscar/backends/pool.py", line 541, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/admin/mars-ant/mars/oscar/backends/pool.py", line 333, in _run_coro
    return await coro
  File "/home/admin/mars-ant/mars/oscar/api.py", line 120, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 507, in __on_receive__
    raise ex
  File "mars/oscar/core.pyx", line 500, in mars.oscar.core._BaseActor.__on_receive__
    return await self._handle_actor_result(result)
  File "mars/oscar/core.pyx", line 385, in _handle_actor_result
    task_result = await coros[0]
  File "mars/oscar/core.pyx", line 428, in mars.oscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "mars/oscar/core.pyx", line 429, in mars.oscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "mars/oscar/core.pyx", line 434, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await gen.athrow(*res)
  File "/home/admin/mars-ant/mars/services/subtask/worker/runner.py", line 125, in run_subtask
    result = yield self._running_processor.run(subtask)
  File "mars/oscar/core.pyx", line 439, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await self._handle_actor_result(res)
  File "mars/oscar/core.pyx", line 359, in _handle_actor_result
    result = await result
  File "/home/admin/mars-ant/mars/oscar/backends/context.py", line 190, in send
    return self._process_result_message(result)
  File "/home/admin/mars-ant/mars/oscar/backends/context.py", line 70, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/admin/mars-ant/mars/oscar/backends/pool.py", line 541, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/admin/mars-ant/mars/oscar/backends/pool.py", line 333, in _run_coro
    return await coro
  File "/home/admin/mars-ant/mars/oscar/api.py", line 120, in __on_receive__
    return await super().__on_receive__(message)
  File "mars/oscar/core.pyx", line 507, in __on_receive__
    raise ex
  File "mars/oscar/core.pyx", line 500, in mars.oscar.core._BaseActor.__on_receive__
    return await self._handle_actor_result(result)
  File "mars/oscar/core.pyx", line 385, in _handle_actor_result
    task_result = await coros[0]
  File "mars/oscar/core.pyx", line 428, in mars.oscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "mars/oscar/core.pyx", line 429, in mars.oscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "mars/oscar/core.pyx", line 434, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await gen.athrow(*res)
  File "/home/admin/mars-ant/mars/services/subtask/worker/processor.py", line 616, in run
    result = yield self._running_aio_task
  File "mars/oscar/core.pyx", line 439, in mars.oscar.core._BaseActor._run_actor_async_generator
    res = await self._handle_actor_result(res)
  File "mars/oscar/core.pyx", line 359, in _handle_actor_result
    result = await result
  File "/home/admin/mars-ant/mars/services/subtask/worker/processor.py", line 463, in run
    await self._execute_graph(chunk_graph)
  File "/home/admin/mars-ant/mars/services/subtask/worker/processor.py", line 223, in _execute_graph
    await to_wait
  File "/home/admin/mars-ant/mars/lib/aio/_threads.py", line 36, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/home/admin/.pyenv/versions/3.7.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/admin/mars-ant/mars/services/subtask/worker/tests/subtask_processor.py", line 70, in _execute_operand
    super()._execute_operand(ctx, op)
  File "/home/admin/mars-ant/mars/core/mode.py", line 77, in _inner
    return func(*args, **kwargs)
  File "/home/admin/mars-ant/mars/services/subtask/worker/processor.py", line 191, in _execute_operand
    return execute(ctx, op)
  File "/home/admin/mars-ant/mars/core/operand/core.py", line 485, in execute
    result = executor(results, op)
  File "/home/admin/mars-ant/mars/dataframe/groupby/sample.py", line 323, in execute
    errors=op.errors,
  File "/home/admin/mars-ant/mars/dataframe/groupby/sample.py", line 314, in <listcomp>
    sample_pd[iloc_col].to_numpy()
  File "/home/admin/mars-ant/mars/dataframe/groupby/sample.py", line 69, in _sample_groupby_iter
    n=n, frac=frac, replace=replace, weights=w, random_state=random_state
  File "/home/admin/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pandas/core/generic.py", line 5365, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice
ValueError: [address=127.0.0.1:42482, pid=84916] Cannot take a larger sample than population when 'replace=False'
```

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version `3.7.7`
2. The version of Mars you use `Latest master`
3. Versions of crucial packages, such as numpy, scipy and pandas `numpy==1.21.5 pandas==1.3.5`
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Expected behavior**

**Additional context**

I added some logs and found that the decref stage does not match the incref stage:

The incref stage only increfs the `MapReduceOperand` with `stage == reduce`:

```python
for chunk in subtask.chunk_graph:
    if (
        isinstance(chunk.op, MapReduceOperand)
        and chunk.op.stage == OperandStage.reduce
    ):
        # reducer
        data_keys = chunk.op.get_dependent_data_keys()
        incref_chunk_keys.extend(data_keys)
        # main key incref as well, to ensure existence of meta
        incref_chunk_keys.extend([key[0] for key in data_keys])
```

But, the decref stage will derefs all the matched `MapReduceOperand`:

``` python
# if subtask not executed, rollback incref of predecessors
for inp_subtask in subtask_graph.predecessors(subtask):
    for result_chunk in inp_subtask.chunk_graph.results:
        # for reducer chunk, decref mapper chunks
        if isinstance(result_chunk.op, ShuffleProxy):
            for chunk in subtask.chunk_graph:
                if isinstance(chunk.op, MapReduceOperand):
                    data_keys = chunk.op.get_dependent_data_keys()
                    print(">>>>>>>>>", chunk.op, chunk.op.stage, data_keys)
                    decref_chunk_keys.extend(data_keys)
                    decref_chunk_keys.extend(
                        [key[0] for key in data_keys]
                    )
```

The error data key in above traceback belongs to the a `DataFrameGroupByOperand` with `None` stage:

``` python
>>>>>>>>> DataFrameGroupByOperand <key=7bbacc1ca962ead3202f2ee0d4774909> None ['fba521b5c44e2f43199042f58b5fa971_0']
```

**Comment by qinxuye** [comment]
The incref & decref logic are modified in #2900 that not all mapper meta is recorded, and in that PR, the log disappeared when `--log-cli-level=debug` is on.
