### ISSUE TITLE
[BUG] AttributeError: module 'asyncio' has no attribute 'create_task'

### ISSUE THREAD

**Issue by zhangyuqi-1** [mars-project/mars#3142]
import mars.dataframe as md
Traceback (most recent call last):
  File "F:/work/cii-pip-algo/mars_demo.py", line 3, in <module>
    import mars.tensor as mt
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\__init__.py", line 18, in <module>
    from .core.context import get_context
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\core\__init__.py", line 17, in <module>
    from .base import ExecutionError
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\core\base.py", line 18, in <module>
    from ..serialization.core import Placeholder, fast_id
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\serialization\__init__.py", line 15, in <module>
    from .aio import AioSerializer, AioDeserializer
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\serialization\aio.py", line 23, in <module>
    from ..utils import lazy_import
  File "C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\mars\utils.py", line 91, in <module>
    _create_task = asyncio.create_task
AttributeError: module 'asyncio' has no attribute 'create_task'

**Comment by zhangyuqi-1** [comment]
好的，我明白了，感谢答复。我使用的是Python 3.6。

**Comment by wjsi** [comment]
No further responses, close.
