### ISSUE TITLE
[BUG] mars.new_session() AttributeError: '_LiteralSpecialForm' object has no attribute 'no_default'

### ISSUE THREAD

**Issue by HeloWong** [mars-project/mars#3309]
When run python -c "import mars; mars.new_session()", it happened "AttributeError: '_LiteralSpecialForm' object has no attribute 'no_default'"

my python version is: 3.9.12 windows10 and run on virtual environment
Mars version is : 0.9.0 and installed by pip install pymars 
Numpy version is : 1.24.1
Scipy version: 1.9.3
Scikit-learn: 1.2.0
Pandas vesion 1.5.2

Stack error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\session.py", line 2039, in new_session
    session = SyncSession.init(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\session.py", line 1636, in init
    isolated_session = fut.result()
  File "D:\Anaconda3\envs\tf\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\Anaconda3\envs\tf\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\session.py", line 847, in init
    await new_cluster_in_isolation(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\local.py", line 91, in new_cluster_in_isolation
    await cluster.start()
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\local.py", line 216, in start
    await self._start_supervisor_pool()
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\local.py", line 240, in _start_supervisor_pool
    self._supervisor_pool = await create_supervisor_actor_pool(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\deploy\oscar\pool.py", line 39, in create_supervisor_actor_pool
    return await mo.create_actor_pool(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\oscar\api.py", line 58, in create_actor_pool
    return await get_backend(scheme).create_actor_pool(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\oscar\backends\mars\backend.py", line 61, in create_actor_pool
    return await create_actor_pool(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\oscar\backends\pool.py", line 1436, in create_actor_pool
    pool: MainActorPoolType = await pool_cls.create(
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\oscar\backends\pool.py", line 1177, in create
    pool: MainActorPoolType = await super().create(config)
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\oscar\backends\pool.py", line 715, in create
    __import__(mod, globals(), locals(), [])
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\dataframe\__init__.py", line 39, in <module>
    from .datasource.date_range import date_range
  File "E:\Documents\project\BCI\venv\lib\site-packages\mars\dataframe\datasource\date_range.py", line 303, in <module>
    closed=NoDefault.no_default,
  File "D:\Anaconda3\envs\tf\lib\typing.py", line 710, in __getattr__
    return getattr(self.__origin__, attr)
AttributeError: '_LiteralSpecialForm' object has no attribute 'no_default'

**Comment by fyrestone** [comment]
Could you try the latest master?

**Comment by HeloWong** [comment]
latest master branch is OK

**Comment by HeloWong** [comment]
Thanks
