### ISSUE TITLE
[BUG] Submit job failed if client's python version is inconsistent with server's

### ISSUE THREAD

**Issue by hekaisheng** [mars-project/mars#337]
**Describe the bug**
In distributed mode, if server side uses python3 and client submit job by python2, the job will fail when deserialize the graph on the server side.

**To Reproduce**
I create a distributed cluster and use python2 to submit the job.

``` Python
In [3]: from mars.session import new_session

In [4]: sess = new_session('***endpoint***')

In [5]: a = mt.ones((10, 10), chunk_size=3)

In [6]: b = a.dot(a)

In [7]: sess.run(b)
---------------------------------------------------------------------------
ExecutionFailed                           Traceback (most recent call last)
<ipython-input-7-dfa6f3b19a16> in <module>()
----> 1 sess.run(b)

/usr/local/lib/python2.7/site-packages/mars/session.pyc in run(self, *tensors, **kw)
    115         # execute the non-executed tensors
    116         if idx_to_run_tensors:
--> 117             execute_result = self._sess.run(*idx_to_run_tensors.values(), **kw)
    118             if execute_result:
    119                 # fetch is True

/usr/local/lib/python2.7/site-packages/mars/web/session.pyc in run(self, *tensors, **kw)
    130             try:
    131                 time.sleep(1)
--> 132                 if self._check_response_finished(graph_url):
    133                     break
    134             except KeyboardInterrupt:

/usr/local/lib/python2.7/site-packages/mars/web/session.pyc in _check_response_finished(self, graph_url)
     99                     (resp_json['msg'], traceback))
    100             else:
--> 101                 raise ExecutionFailed('Graph execution failed with unknown reason.')
    102         raise ExecutionStateUnknown(
    103             'Unknown graph execution state %s' % resp_json['state'])

ExecutionFailed: Graph execution failed with unknown reason.

```
Server's error stack:

```
2019-04-11 11:56:26,709 mars.scheduler.graph 84 DEBUG    Graph 730e3a9e-f854-4e15-a59f-06a8848860fa state from GraphState.UNSCHEDULED to GraphState.PREPARING.
2019-04-11 11:56:26,737 mars.scheduler.graph 84 ERROR    Failed to start graph execution.
Traceback (most recent call last):
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/scheduler/graph.py", line 240, in execute_graph
    self.prepare_graph()
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/scheduler/graph.py", line 315, in prepare_graph
    tensor_graph = deserialize_graph(self._serialized_tensor_graph)
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/utils.py", line 216, in deserialize_graph
    return graph_cls.from_json(json_obj)
  File "mars/graph.pyx", line 419, in mars.graph.DirectedGraph.from_json
  File "mars/serialize/core.pyx", line 537, in mars.serialize.core.Serializable.from_json
  File "mars/serialize/core.pyx", line 508, in mars.serialize.core.Serializable.deserialize
  File "mars/serialize/core.pyx", line 649, in mars.serialize.core.Provider.deserialize_model
  File "mars/serialize/core.pyx", line 143, in mars.serialize.core.Field.deserialize
  File "mars/serialize/jsonserializer.pyx", line 479, in mars.serialize.jsonserializer.JsonSerializeProvider.deserialize_field
  File "mars/serialize/core.pyx", line 508, in mars.serialize.core.Serializable.deserialize
  File "mars/serialize/core.pyx", line 649, in mars.serialize.core.Provider.deserialize_model
  File "mars/serialize/core.pyx", line 143, in mars.serialize.core.Field.deserialize
  File "mars/serialize/jsonserializer.pyx", line 472, in mars.serialize.jsonserializer.JsonSerializeProvider.deserialize_field
  File "mars/serialize/core.pyx", line 577, in mars.serialize.core.AttributeAsDict.deserialize
  File "mars/serialize/core.pyx", line 656, in mars.serialize.core.Provider.deserialize_attribute_as_dict
  File "mars/serialize/core.pyx", line 646, in mars.serialize.core.Provider.deserialize_model
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/operands/core.py", line 77, in __new__
    module, tp = op_id.split('.', 1)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by qinxuye** [comment]
There must be an api to tell the client the cluster is based on 2 or 3, if the versions are inconsistent, error should be raised.
