### ISSUE TITLE
[BUG] worker chunkstore error cause failure

### ISSUE THREAD

**Issue by chineking** [mars-project/mars#370]
**Describe the bug**

```

Traceback (most recent call last):
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/scheduler/operand.py", line 461, in _rejecter
    six.reraise(*exc)
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/lib/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/promise.py", line 92, in _wrapped
    result = func(*args, **kwargs)
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/utils.py", line 288, in _wrapped
    return func(*args, **kwargs)
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/worker/calc.py", line 72, in _try_put_chunk
    ref = self._chunk_store.put(session_id, chunk_key, _calc_result_cache[chunk_key][1])
  File "/home/admin/work/_public-mars-0.1.1.zip/mars/worker/chunkstore.py", line 184, in put
    value = DataTuple(*value)
TypeError: tuple() takes at most 1 argument (2 given)
```

**To Reproduce**

Can reproduce for branch 0.1 .

**Comment by wjsi** [comment]
Fixed for v0.1, not a problem for v0.2
