### ISSUE TITLE
[BUG]SetValue on 1-d array doesn't work with local cluster session

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#441]
**Describe the bug**

`__setitem__` on 1-d tensor doesn't work with local cluster session.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: Python 3.7.3, on darwin
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.

```
Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    print(session.run(x))
  File "/Users/hetao/mars/mars/session.py", line 115, in run
    result = self._sess.run(*tileables, **kw)
  File "/Users/hetao/mars/mars/deploy/local/session.py", line 86, in run
    self._api.submit_graph(self._session_id, json.dumps(graph.to_json()),
  File "mars/graph.pyx", line 443, in mars.graph.DirectedGraph.to_json
    return self.serialize().to_json(obj=json_obj)
  File "mars/serialize/core.pyx", line 634, in mars.serialize.core.Serializable.to_json
    return self.serialize(provider, obj=obj)
  File "mars/serialize/core.pyx", line 605, in mars.serialize.core.Serializable.serialize
    return provider.serialize_model(self, obj=obj)
  File "mars/serialize/core.pyx", line 723, in mars.serialize.core.Provider.serialize_model
    field.serialize(self, model_instance, obj)
  File "mars/serialize/core.pyx", line 150, in mars.serialize.core.Field.serialize
    cpdef serialize(self, Provider provider, model_instance, obj):
  File "mars/serialize/core.pyx", line 151, in mars.serialize.core.Field.serialize
    return provider.serialize_field(self, model_instance, obj)
  File "mars/serialize/jsonserializer.pyx", line 450, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
    new_obj.append(val.serialize(self, dict()))
  File "mars/serialize/core.pyx", line 605, in mars.serialize.core.Serializable.serialize
    return provider.serialize_model(self, obj=obj)
  File "mars/serialize/core.pyx", line 723, in mars.serialize.core.Provider.serialize_model
    field.serialize(self, model_instance, obj)
  File "mars/serialize/core.pyx", line 150, in mars.serialize.core.Field.serialize
    cpdef serialize(self, Provider provider, model_instance, obj):
  File "mars/serialize/core.pyx", line 151, in mars.serialize.core.Field.serialize
    return provider.serialize_field(self, model_instance, obj)
  File "mars/serialize/jsonserializer.pyx", line 434, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
    value.serialize(self, new_obj)
  File "mars/serialize/core.pyx", line 669, in mars.serialize.core.AttributeAsDict.serialize
    return provider.serialize_attribute_as_dict(self, obj=obj)
  File "mars/serialize/core.pyx", line 728, in mars.serialize.core.Provider.serialize_attribute_as_dict
    return self.serialize_model(model_instance, obj=obj)
  File "mars/serialize/core.pyx", line 723, in mars.serialize.core.Provider.serialize_model
    field.serialize(self, model_instance, obj)
  File "mars/serialize/core.pyx", line 150, in mars.serialize.core.Field.serialize
    cpdef serialize(self, Provider provider, model_instance, obj):
  File "mars/serialize/core.pyx", line 151, in mars.serialize.core.Field.serialize
    return provider.serialize_field(self, model_instance, obj)
  File "mars/serialize/jsonserializer.pyx", line 461, in mars.serialize.jsonserializer.JsonSerializeProvider.serialize_field
    obj[tag] = self._serialize_value(val, field.type, weak_ref=field.weak_ref)
  File "mars/serialize/jsonserializer.pyx", line 390, in mars.serialize.jsonserializer.JsonSerializeProvider._serialize_value
    return self._serialize_untyped_value(value, weak_ref=weak_ref)
  File "mars/serialize/jsonserializer.pyx", line 386, in mars.serialize.jsonserializer.JsonSerializeProvider._serialize_untyped_value
    raise TypeError('Unknown type to serialize: {0}'.format(type(value)))
TypeError: Unknown type to serialize: <class 'numpy.int64'>
```

5. Minimized code to reproduce the error.

```
from mars.deploy.local import new_cluster
from mars.session import new_session
cluster = new_cluster()
session = new_session(cluster.endpoint)

x = mt.tensor(np.array(range(9)), chunk_size=2)
x[1] = 111
x[2] = 222
x[3] = 333
print(session.run(x))
```

**Expected behavior**

```
array([  0, 111, 222, 333,   4,   5,   6,   7,   8])
```

**Additional context**

**Comment by qinxuye** [comment]
Solved in #488,  I will close this issue, feel free to reopen if issue exists still.
