### ISSUE TITLE
[BUG]Error when from mars.deploy.local import new_cluster in 0.2.0b1

### ISSUE THREAD

**Issue by xiaonans** [mars-project/mars#446]
**Describe the bug**
A error occurred when importing new_cluster

**To Reproduce**
In python:
from mars.deploy.local import new_cluster

**Additional context**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiaonans/projects/mars/mars/mars/deploy/local/__init__.py", line 17, in <module>
    from .core import new_cluster
  File "/home/xiaonans/projects/mars/mars/mars/deploy/local/core.py", line 27, in <module>
    from ...scheduler.service import SchedulerService
  File "/home/xiaonans/projects/mars/mars/mars/scheduler/service.py", line 29, in <module>
    from .node_info import NodeInfoActor
  File "/home/xiaonans/projects/mars/mars/mars/scheduler/node_info.py", line 19, in <module>
    from ..node_info import gather_node_info
  File "/home/xiaonans/projects/mars/mars/mars/node_info.py", line 41, in <module>
    import cudf
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 22, in <module>
    from cudf.utils import cudautils, queryutils, applyutils, utils
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/utils/applyutils.py", line 13, in <module>
    from cudf.dataframe.series import Series
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/dataframe/series.py", line 14, in <module>
    from .index import Index, RangeIndex, as_index
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/dataframe/index.py", line 15, in <module>
    from .numerical import NumericalColumn
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/dataframe/numerical.py", line 18, in <module>
    from cudf._sort import get_sorted_inds
  File "/home/xiaonans/.local/lib/python3.6/site-packages/cudf/_sort.py", line 7, in <module>
    import cudf.bindings.sort as cpp_sort
  File "__init__.pxd", line 918, in init cudf.bindings.sort
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by wjsi** [comment]
The error message shows that your cudf is not installed properly, hence you need to make sure that ``import cudf`` works well under your Python installation. This error has nothing to do with Mars. If you feel hard to resolve this error, you may comment out the line ``import cudf`` as it is currently not used in master branch of Mars.
