### ISSUE TITLE
[BUG] Inconsistency of __setitem__ with numpy

### ISSUE THREAD

**Issue by sighingnow** [mars-project/mars#499]
**Describe the bug**

The behavior is inconsistent with numpy.

**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version: python 3.7
2. The version of Mars you use: master
3. Versions of crucial packages, such as numpy, scipy and protobuf
4. Full stack of the error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hetao/mars/mars/tensor/expressions/indexing/setitem.py", line 113, in _setitem
    value = broadcast_to(value, shape).astype(a.dtype)
  File "/Users/hetao/mars/mars/tensor/expressions/base/broadcast_to.py", line 103, in broadcast_to
    raise ValueError('input operand has more dimensions than allowed by the axis remapping')
ValueError: input operand has more dimensions than allowed by the axis remapping
>>>
```

5. Minimized code to reproduce the error.

```python
import numpy as np
import mars.tensor as mt

x = np.zeros((4, 4))
x[1] = np.array([[1,2,3,4]]) # works

x = mt.zeros((4, 4))
x[1] = np.array([[1,2,3,4]]) # raise an exception
``` 

**Expected behavior**

The behavior should be consistent with numpy. The value `np.array([[1,2,3,4]])` should be firstly `broadcast_to` as `[1, 4]`, then `reshape` it as `[4]`.

**Additional context**

**Comment by qinxuye** [comment]
```
The behavior should be consistent with numpy. The value np.array([[1,2,3,4]]) should be firstly broadcast_to as [1, 4], then reshape it as [4].
```
Do you find the behavior from source code or somewhere? @sighingnow
