### ISSUE TITLE
[BUG] gevent is not required for mars client but we wrongly import a module use gevent 

### ISSUE THREAD

**Issue by chineking** [mars-project/mars#53]
**Describe the bug**

gevent is not required for mars client but we wrongly import a module use gevent which leads to a ModuleNotFoundError.

**To Reproduce**

Start a fresh environment by conda create. After `pip install pymars`, run

```python
>>> import mars.tensor as mt
>>> a = mt.random.rand(100, 100)
>>> a.sum().execute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/qinxuye/Workspace/mars/mars/tensor/core.py", line 441, in execute
    from ..session import Session
  File "/Users/qinxuye/Workspace/mars/mars/session.py", line 22, in <module>
    from .api import MarsAPI
  File "/Users/qinxuye/Workspace/mars/mars/api.py", line 18, in <module>
    from .cluster_info import ClusterInfoActor
  File "/Users/qinxuye/Workspace/mars/mars/cluster_info.py", line 20, in <module>
    from . import kvstore
  File "/Users/qinxuye/Workspace/mars/mars/kvstore.py", line 2, in <module>
    from gevent.event import Event
ModuleNotFoundError: No module named 'gevent'
```

**Expected behavior**

Either we shouldn't import these modules or catch the ImportError.

**Additional context**

We must add tests for this case which proposed in #52 .

**Comment by chineking** [comment]
The unnecessary import should have been detected after enable flake8 check mentioned in #22 , we should make sure the job can be done before 0.1.0 released.
