### ISSUE TITLE
[BUG][DISTRIBUTED] run parts of svd results will cause serialize error

### ISSUE THREAD

**Issue by chineking** [mars-project/mars#8]
**Describe the bug**

Some tensor op can generate multiple outputs, svd etc. Assume u, s, v is the result tensors for SVD decomposition, for the distributed setting, if we only run parts of the tensors, for example, u and s, the KeyError will be raised which I guess is all due to the serialization issue.

**To Reproduce**

I start one scheduler, worker and web on my laptop.

On the client side:

```python
In [3]: from mars.session import new_session

In [4]: session  = new_session('http://0.0.0.0:61378')

In [5]: a = mt.random.rand(10, 20)

In [6]: dec = np.linalg.svd(a)

In [7]: dec = mt.linalg.svd(a)

In [8]: session.run(dec[:2])
```

The client will hang.

On the scheduler side, we can get the error:

```python
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "mars/actors/pool/gevent_pool.pyx", line 88, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    cpdef object fire_run(self):
  File "mars/actors/pool/gevent_pool.pyx", line 91, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    with self.lock:
  File "mars/actors/pool/gevent_pool.pyx", line 102, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    raise
  File "mars/actors/pool/gevent_pool.pyx", line 96, in mars.actors.pool.gevent_pool.ActorExecutionContext.fire_run
    res = actor.on_receive(message_ctx.message)
  File "mars/actors/core.pyx", line 108, in mars.actors.core.FunctionActor.on_receive
    cpdef on_receive(self, message):
  File "mars/actors/core.pyx", line 110, in mars.actors.core.FunctionActor.on_receive
    return getattr(self, method)(*args, **kwargs)
  File "/Users/qinxuye/Workspace/mars/mars/scheduler/graph.py", line 153, in execute_graph
    self.prepare_graph()
  File "/Users/qinxuye/Workspace/mars/mars/scheduler/graph.py", line 207, in prepare_graph
    tensor_graph = deserialize_graph(self._serialized_tensor_graph)
  File "/Users/qinxuye/Workspace/mars/mars/utils.py", line 403, in deserialize_graph
    return DirectedGraph.from_json(json_obj)
  File "mars/graph.pyx", line 415, in mars.graph.DirectedGraph.from_json
    return cls.deserialize(SerialiableGraph.from_json(json_obj))
  File "mars/serialize/core.pyx", line 537, in mars.serialize.core.Serializable.from_json
    return cls.deserialize(provider, obj)
  File "mars/serialize/core.pyx", line 510, in mars.serialize.core.Serializable.deserialize
    [cb(key_to_instance) for cb in callbacks]
  File "mars/serialize/jsonserializer.pyx", line 176, in mars.serialize.jsonserializer.JsonSerializeProvider._deserialize_list.cb.inner
    o = subs[v.key, v.id]
KeyError: ('9e2478de2695b727435601490ebaa999', '5219323976')
2018-12-07T11:14:35Z <Greenlet "Greenlet-0" at 0x138f5a448: <built-in method fire_run of mars.actors.pool.gevent_pool.ActorExecutionContext object at 0x139002cc8>> failed with KeyError
```

**Comment by chineking** [comment]
The failure can be produced without starting the distributed runtime by the code below.

```python
a = mt.random.rand(9, 6, chunks=(3, 6))
U, s, V = mt.linalg.svd(a)

graph = DirectedGraph()
U.build_graph(tiled=False, graph=graph)
s.build_graph(tiled=False, graph=graph)

new_graph = DirectedGraph.from_json(graph.to_json())
```

I will add it to the expression tests and try to fix it.

**Comment by chineking** [comment]
This issue is not solved completely, for example

```python
a = mt.random.rand(9, 6, chunks=(3, 6))
U, s, V = mt.linalg.svd(a)

graph = DirectedGraph()
(U + 1).build_graph(tiled=False, graph=graph)
(s + 1).build_graph(tiled=False, graph=graph)

new_graph = DirectedGraph.from_json(graph.to_json())
```

We do some calculation on the U and s, the serialize error will throw again, I will try to fix it.
